#+STARTUP: nofold
#+title: Emacs Config
#+author: Azizul Islam
#+email: azizul7m@gmail.com
#+OPTIONS: toc:2
* TABLE OF CONTENT                                                     :toc:
- [[#vanila-emacs-config][VANILA *EMACS* CONFIG]]
- [[#packages-manager-and-other-script][PACKAGES MANAGER AND OTHER SCRIPT]]
  - [[#import-script-directory][IMPORT SCRIPT DIRECTORY]]
  - [[#require-scripts][REQUIRE SCRIPTS]]
- [[#evil-mode][EVIL MODE]]
- [[#keybinding][KEYBINDING]]
- [[#ligature][LIGATURE]]
- [[#search-engine][SEARCH ENGINE]]
  - [[#vertico][VERTICO]]
  - [[#vertico-posframe][VERTICO-POSFRAME]]
  - [[#orderless][ORDERLESS]]
  - [[#consult][CONSULT]]
  - [[#embark][EMBARK]]
  - [[#wgrep][WGREP]]
  - [[#marginalia][MARGINALIA]]
- [[#diminish][DIMINISH]]
- [[#whichkey][WHICHKEY]]
- [[#completion-stuff][COMPLETION STUFF]]
  - [[#company-mode][COMPANY MODE]]
- [[#org-mode][ORG-MODE]]
- [[#development][DEVELOPMENT]]
  - [[#lsp][LSP]]
  - [[#debug][DEBUG]]
  - [[#language][LANGUAGE]]
  - [[#eglot][Eglot]]
- [[#git][GIT]]
- [[#popper][POPPER]]
- [[#file-browser][FILE BROWSER]]
  - [[#dired][DIRED]]
  - [[#treemacs][Treemacs]]
  - [[#projectile][PROJECTILE]]
- [[#terminal][TERMINAL]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm toggle]]
  - [[#eshell][Eshell]]
- [[#snippets][SNIPPETS]]
- [[#rainbow][RAINBOW]]
- [[#sudo-edit][SUDO EDIT]]
- [[#tldr][TlDR]]
- [[#heighlight-todo-list][HEIGHLIGHT TODO LIST]]
- [[#transparency][TRANSPARENCY]]
- [[#ui-stuff][UI STUFF]]
  - [[#icons][ICONS]]
  - [[#theme][THEME]]
  - [[#dashboard][DASHBOARD]]
  - [[#fonts][FONTS]]
  - [[#indent][INDENT]]
  - [[#formating][FORMATING]]
  - [[#perspective][PERSPECTIVE]]

* VANILA *EMACS* CONFIG
 #+BEGIN_SRC elisp
   (menu-bar-mode -1)
   (tool-bar-mode -1)
   (fringe-mode -1)
   (scroll-bar-mode -1)
   (electric-pair-mode 1) ;; auto paire
   (global-subword-mode 1) ;; global line number
   (global-visual-line-mode t)
   (global-display-line-numbers-mode 1)
   (global-auto-revert-mode t)  ;; Automatically show changes if the file has changed

   (setq use-dialog-box nil)
   (setq use-file-dialog nil)
   (setq make-backup-files nil)
   (setq auto-save-default nil)
   (setq locale-coding-system 'utf-8)
   (defalias 'yes-or-no-p 'y-or-n-p)

  (global-set-key [escape] 'keyboard-escape-quit)
  (global-set-key (kbd "C-=") 'text-scale-increase)
  (global-set-key (kbd "C--") 'text-scale-decrease)
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)

 (setq visual-fill-column-width 180
       visual-fill-column-center-text t) ;; ;; Configure fill width
#+END_SRC
*** locale
#+begin_src elisp
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+end_src
* PACKAGES MANAGER AND OTHER SCRIPT
** IMPORT SCRIPT DIRECTORY
#+BEGIN_SRC elisp
(defvar scripts-dir (expand-file-name "scripts" user-emacs-directory))
(add-to-list 'load-path scripts-dir)
#+end_src
** REQUIRE SCRIPTS
#+begin_src emacs-lisp
(require 'elpaca-setup)
(require 'buffer_move)
#+END_SRC
* EVIL MODE
#+begin_src emacs-lisp
(use-package evil
    :init      ;; tweak evil's configuration before loading it
    (setq evil-want-integration t  ;; This is optional since it's already set to t by default.
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)  ;; Adds vim-like C-r redo functionality
    (evil-mode))
(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer  ))
  (add-to-list 'evil-collection-mode-list 'help) ;; evilify help mode
  (evil-collection-init))
;; Using RETURN to follow links in Org/Evil 
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))
  ;; Setting RETURN key in org-mode to follow links
(setq org-return-follows-link  t)

(use-package evil-tutor)
;;Mapping "jk" to Escape in Emacs' evil-mode
(use-package evil-escape
  :config
  ;; Set the key sequence you want to use for escaping
  (setq-default evil-escape-key-sequence "jk")
  ;; Adjust the delay if needed
  (setq-default evil-escape-delay 0.2)
  ;; Enable Evil Escape mode globally
  (evil-escape-mode 1))
#+end_src
* KEYBINDING
Goto this file -> [[file:./keybinding.el][KEYBINDING]]
key binding with the help *general* package.
#+begin_src emacs-lisp
(load (expand-file-name "keybinding.el" user-emacs-directory))
#+end_src
*** Key-chord
#+begin_src emacs-lisp
;(use-package key-chord
;  :ensure t)
;(key-chord-mode 1)
#+end_src
* LIGATURE
#+begin_src emacs-lisp
(use-package ligature
  :ensure t
  :config
  ;; Enable the "www" ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))
  (ligature-set-ligatures '(prog-mode
                           org-mode)
                          '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>"
                                       ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                                       "!!." ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                                       "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                                       "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                                       "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                                       "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                                       "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                                       ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                                       "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                                       "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                                       "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
                                       "\\\\" "://"))
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi"))
  (global-ligature-mode t))
#+end_src
* SEARCH ENGINE
** VERTICO
The `vertico' package applies a vertical layout to the minibuffer. It also pops up the minibuffer eagerly so we can see the available
options without further interactions.  This package is very fast and "just works", though it also is highly customisable in case we
need to modify its behaviour.
#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :config
  (setq vertico-cycle t)
  (setq vertico-resize nil)
  (vertico-mode 1))
#+end_src
** VERTICO-POSFRAME
#+begin_src emacs-lisp
(use-package vertico-posframe)
(setq vertico-multiform-commands
      '((consult-line
         posframe
         (vertico-posframe-poshandler . posframe-poshandler-frame-top-center)
         (vertico-posframe-border-width . 15)
         ;; NOTE: This is useful when emacs is used in both in X and
         ;; terminal, for posframe do not work well in terminal, so
         ;; vertico-buffer-mode will be used as fallback at the
         ;; moment.
         (vertico-posframe-fallback-mode . vertico-buffer-mode))
        (t posframe)))
(setq vertico-posframe-parameters '((left-fringe . 5) (right-fringe . 5)))
(setq vertico-posframe-mode 1)
#+end_src
** ORDERLESS
The `orderless' package lets the minibuffer use an out-of-order pattern matching algorithm.  It matches space-separated words or
regular expressions in any order.  In its simplest form, something like "ins pac" matches `package-menu-mark-install' as well as
`package-install'.  This is a powerful tool because we no longer need to remember exactly how something is named.
#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :config
  (setq completion-styles '(orderless basic)))
#+end_src
** CONSULT
The `consult' package provides lots of commands that are enhanced variants of basic, built-in functionality.  One of the headline
features of `consult' is its preview facility, where it shows in another Emacs window the context of what is currently matched in
the minibuffer.  Here I define key bindings for some commands you may find useful.  The mnemonic for their prefix is "alternative
search" (as opposed to the basic C-s or C-r keys).
#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :bind (;; A recursive grep
         ("M-s M-g" . consult-grep)
         ;; Search for files names recursively
         ("M-s M-f" . consult-find)
         ;; Search through the outline (headings) of the file
         ("M-s M-o" . consult-outline)
         ;; Search the current buffer
         ("M-s M-l" . consult-line)
         ;; Switch to another buffer, or bookmarked file, or recently
         ;; opened file.
         ("M-s M-b" . consult-buffer)))
#+end_src
** EMBARK
;; The `embark' package lets you target the thing or context at point ;; and select an action to perform on it.  Use the `embark-act'
;; command while over something to find relevant commands.
#+begin_src emacs-lisp
(use-package embark
  :ensure t
  :bind (("C-." . embark-act)
         :map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export)))

;; The `embark-consult' package is glue code to tie together `embark'
;; and `consult'.
(use-package embark-consult
  :ensure t)
#+end_src
** WGREP
The `wgrep' packages lets us edit the results of a grep search while inside a `grep-mode' buffer.  All we need is to toggle the
editable mode, make the changes, and then type C-c C-c to confirm
or C-c C-k to abort.
#+begin_src emacs-lisp
(use-package wgrep
  :ensure t
  :bind ( :map grep-mode-map
          ("e" . wgrep-change-to-wgrep-mode)
          ("C-x C-q" . wgrep-change-to-wgrep-mode)
          ("C-c C-c" . wgrep-finish-edit)))

;; The built-in `savehist-mode' saves minibuffer histories.  Vertico can then use that information to put recently selected options at the top.
;; Further reading: https://protesilaos.com/emacs/dotemacs#h:25765797-27a5-431e-8aa4-cc890a6a913a
(savehist-mode 1)

;; The built-in `recentf-mode' keeps track of recently visited files.  You can then access those through the `consult-buffer' interface or
;; with `recentf-open'/`recentf-open-files'.
;; I do not use this facility, because the files I care about are either in projects or are bookmarked.
(recentf-mode 1)
#+end_src
** MARGINALIA
#+begin_src emacs-lisp
(use-package marginalia
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'right)
  :init
  (marginalia-mode 1))
#+end_src
* DIMINISH
This package implements hiding or abbreviation of the mode line displays (lighters) of minor-modes.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src
* WHICHKEY
#+begin_src emacs-lisp
(use-package which-key
  :init
    (which-key-mode 1)
  :config
  (setq which-key-side-window-location 'bottom
	  which-key-sort-order #'which-key-key-order-alpha
	  which-key-sort-uppercase-first nil
	  which-key-add-column-padding 1
	  which-key-max-display-columns nil
	  which-key-min-display-lines 6
	  which-key-side-window-slot -10
	  which-key-side-window-max-height 0.25
	  which-key-idle-delay 0.8
	  which-key-max-description-length 25
	  which-key-allow-imprecise-window-fit nil
	  which-key-separator " → " ))
#+end_src
* COMPLETION STUFF
** COMPANY MODE
#+begin_src emacs-lisp
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :diminish
  :hook (company-mode . company-box-mode))


#+end_src
* ORG-MODE
#+begin_src emacs-lisp
;; Otherwise, org-tempo is broken when you try to <s TAB...
(add-hook 'org-mode-hook (lambda ()
           (setq-local electric-pair-inhibit-predicate
                   `(lambda (c)
                  (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
#+end_src
*** Bullets
#+begin_src emacs-lisp
(use-package org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))) 
#+end_src
*** CUSTOMS FACE
  #+begin_src emacs-lisp
    (custom-set-faces
     '(org-level-1 ((t (:inherit outline-1 :height 1.3))))
     '(org-level-2 ((t (:inherit outline-2 :height 1.25))))
     '(org-level-3 ((t (:inherit outline-3 :height 1.225))))
     '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
     '(org-level-5 ((t (:inherit outline-5 :height 1.15))))
     '(org-level-6 ((t (:inherit outline-5 :height 1.125))))
     '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
  #+end_src
*** Org-juarnal
#+begin_export emacs-lisp
(use-package org-journal
  :ensure t
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq
      org-journal-dir "~/.notes/org/journal"
      org-journal-date-prefix "#+TITLE: "
      org-journal-time-format "%I:%M %p "
      org-journal-time-prefix "* "
      org-journal-date-format "%A, %d/%m/%Y"
      org-journal-file-format "%d-%m-%Y.org"))
    #+end_export
*** Org-Roam
#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (file-truename "~/.notes/org"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ("C-c n j" . org-roam-dailies-capture-today)) ;; Dailies
  :config
  ;; If you're using a vertical completion framework, you might want a more informative completion interface
  (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (require 'org-roam-protocol))
#+end_src
*** Org-roam-ui
#+begin_src emacs-lisp
(use-package websocket
    :after org-roam)
(use-package org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src
*** SNIPPET
#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

*** TOC
#+begin_src emacs-lisp

(setq user-full-name "Azizul Islam"
      user-mail-address "azizul7m@gmail.com")

(use-package toc-org
    :commands toc-org-enable
    :init
    (add-hook 'org-mode-hook 'toc-org-enable))
  #+end_src
* DEVELOPMENT
** LSP
** DEBUG
#+begin_src emacs-lisp
  (use-package dap-mode
    :after lsp-mode
    :ensure t
    :defer t)
#+end_src
** LANGUAGE
*** Web mode
#+begin_src emacs-lisp
(use-package web-mode
  :ensure t)

#+end_src
*** Rust
#+begin_src emacs-lisp

(use-package rustic
  :ensure t
  :init
  (setq rustic-lsp-client 'eglot))

(use-package cargo-mode
  :hook
  (rustic-mode . cargo-minor-mode)
  :config
  (setq compilation-scroll-output t))

(use-package separedit
    :ensure (separedit :type git :host github :repo "idcrook/separedit.el")
    :config
    (progn
    (define-key prog-mode-map (kbd "C-c '") #'separedit)
    (setq separedit-default-mode 'markdown-mode)))
#+end_src
**** SOLANA
#+begin_src emacs-lisp
;; (use-package eglot-solana
  ;; :ensure t
  ;; :hook (solana-mode . eglot-ensure))
#+end_src
*** TOML
#+begin_export elisp
(use-package toml-mode
    :ensure t
    :init
    (add-hook 'toml-mode-hook 'eglot-ensure))
#+end_export
*** Nix
#+begin_src emacs-lisp
(use-package nix-mode)
#+end_src

** Eglot
#+begin_src emacs-lisp
#+end_src

* GIT
#+BEGIN_SRC emacs-lisp
(use-package magit
	 :ensure t
	 :defer t)
#+END_SRC
* POPPER
#+begin_src emacs-lisp
(use-package popper
  :ensure t ; or :straight t
  :bind (("C-`"   . popper-toggle)
         ("M-`"   . popper-cycle)
         ("C-M-`" . popper-toggle-type))
  :init
  (setq popper-reference-buffers
        '("\\*Messages\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
          help-mode
          compilation-mode))
  (popper-mode +1)
  (popper-echo-mode +1))                ; For echo area hints
#+end_src
* FILE BROWSER
** DIRED
#+begin_src emacs-lisp
(use-package dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("jepg" . "sxiv")
                                ("png" . "sxiv")
                                ("pdf" . "sioyek")
                                ("mkv" . "vlc")
                                ("mp4" . "vlc"))))
(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src
** Treemacs
#+begin_src emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq
         treemacs-width                           35
         treemacs-recenter-after-project-jump     'always
     )
    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode 'always)
    (when treemacs-python-executable
      (treemacs-git-commit-diff-mode t))

    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple)))

    (treemacs-hide-gitignored-files-mode nil))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t d"   . treemacs-select-directory)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))

(use-package treemacs-evil
  :after (treemacs evil)
  :ensure t)

(use-package treemacs-projectile
  :after (treemacs projectile)
  :ensure t)

(use-package treemacs-icons-dired
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)

(use-package treemacs-magit
  :after (treemacs magit)
  :ensure t)

(use-package treemacs-persp ;;treemacs-perspective if you use perspective.el vs. persp-mode
  :after (treemacs persp-mode) ;;or perspective vs. persp-mode
  :ensure t
  :config (treemacs-set-scope-type 'Perspectives))

#+end_src
** PROJECTILE
#+begin_src emacs-lisp
  (use-package projectile
     :ensure t
     :defer t
     :config
     ;; Enable Projectile globally
     (setq projectile-completion-system 'ido)
     (setq ido-enable-flex-matching t)
     (projectile-mode 1))
#+end_src
* TERMINAL
** Vterm
#+begin_src emacs-lisp
(use-package vterm
:config
(setq shell-file-name "/bin/sh"
      vterm-max-scrollback 5000))
#+end_src
** Vterm toggle
#+begin_src emacs-lisp

(use-package vterm-toggle
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  ;; Modeline customization for vterm buffers
  (defun my-vterm-cleanup-ui ()
    (setq mode-line-format nil)
    (setq mode-line-format-in-non-selected-windows nil))

  (add-hook 'vterm-mode-hook #'my-vterm-cleanup-ui)
  (add-hook 'vterm-mode-hook (lambda () (display-line-numbers-mode 0)))
  
   (add-to-list 'display-buffer-alist
                '((lambda (buffer-or-name _)
                      (let ((buffer (get-buffer buffer-or-name)))
                        (with-current-buffer buffer
                          (or (equal major-mode 'vterm-mode)
                              (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                   (display-buffer-reuse-window display-buffer-at-bottom)
                   (reusable-frames . visible)
                   (window-height . 0.3)))
  )
#+end_src
** Eshell
#+begin_src emacs-lisp
  (use-package eshell-syntax-highlighting
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))
(setq eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src
* SNIPPETS
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t)
(setq yas-global-mode 1)

(setq yas-snippet-dirs
      '("~/.notes/org/snippets")  ;; personal snippets
      )
#+end_src
* RAINBOW
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src
* SUDO EDIT
#+begin_src emacs-lisp
(use-package sudo-edit)
#+end_src
* TlDR
#+begin_src emacs-lisp
(use-package tldr)
#+end_src
* HEIGHLIGHT TODO LIST
#+begin_src emacs-lisp
(use-package hl-todo
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))
#+end_src
* TRANSPARENCY
With Emacs version 29, true transparency has been added.  I have turned transparency off by setting the alpha to ‘100’.  If you want some slight transparency, try setting alpha to ‘90’.  Of course, if you set alpha to ‘0’, the background of Emacs would completely transparent.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 90)) ; For all new frames henceforth
#+end_src
* UI STUFF
** ICONS
#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t
  :if (display-graphic-p)
  :config
  (setq inhibit-compacting-font-caches t))

(use-package all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))

(use-package all-the-icons-completion
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))
#+end_src
** THEME
#+BEGIN_SRC elisp
(use-package hungry-delete
   :ensure t
   :defer t
   :config (global-hungry-delete-mode))
 (use-package doom-themes
 :ensure t
 :config
 (setq doom-themes-enable-bold nil  
         doom-themes-enable-italic t) ; if nil, italics is universally disabled
 (load-theme 'doom-one t)
 (doom-themes-visual-bell-config) ;; Enable flashing mode-line on errors
 (doom-themes-neotree-config) ;; Enable custom neotree them
 (setq doom-themes-treemacs-theme "doom-atom")
 (doom-themes-treemacs-config)
 (doom-themes-org-config))

(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config
  (setq doom-modeline-persp-icon t
    doom-modeline-persp-name t))
#+END_SRC
** DASHBOARD
#+begin_src emacs-lisp
(use-package dashboard
  :ensure t 
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.face")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  :custom 
  (dashboard-modify-heading-icons '((recents . "file-text")
				      (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))
#+end_src
** FONTS
#+begin_src emacs-lisp
(set-face-attribute 'default nil
    :font "Iosevka"
    :height 100
    :weight 'regular)
#+end_src
** INDENT 
#+begin_src emacs-lisp
(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 2)
(eval-after-load 'org-indent '(diminish 'org-indent-mode))
(add-hook 'org-mode-hook 'org-indent-mode)
(setq org-edit-src-content-indentation 0)
(use-package highlight-indent-guides
    :ensure t
    :defer t
    :hook (prog-mode . highlight-indent-guides-mode)
    :config
    (setq highlight-indent-guides-method 'character)
    (setq highlight-indent-guides-character ?\|)
    (setq highlight-indent-guides-responsive 'top))
#+end_src
** FORMATING
#+begin_src emacs-lisp
(use-package format-all
	 :ensure t)
#+end_src
** PERSPECTIVE
#+begin_src emacs-lisp
(use-package perspective
  :custom
  ;; NOTE! I have also set 'SCP =' to open the perspective menu.
  ;; I'm only setting the additional binding because setting it
  ;; helps suppress an annoying warning message.
  (persp-mode-prefix-key (kbd "C-c M-p"))
  :init 
  (persp-mode)
  :config
  ;; Sets a file to write to when we save states
  (setq persp-state-default-file "~/.config/emacs/sessions"))
;; This will group buffers by persp-name in ibuffer.
(add-hook 'ibuffer-hook
          (lambda ()
            (persp-ibuffer-set-filter-groups)
            (unless (eq ibuffer-sorting-mode 'alphabetic)
              (ibuffer-do-sort-by-alphabetic))))
;; Automatically save perspective states to file when Emacs exits.
(add-hook 'kill-emacs-hook #'persp-state-save)
#+end_src
