#+STARTUP: nofold
#+title: Emacs Config
#+author: Azizul Islam
#+email: azizul7m@gmail.com
#+OPTIONS: toc:2
* TABLE OF CONTENT                                                     :toc:
- [[#vanila-emacs-config][VANILA *EMACS* CONFIG]]
- [[#packages-manager-and-other-script][PACKAGES MANAGER AND OTHER SCRIPT]]
  - [[#import-lisp-directory][IMPORT LISP DIRECTORY]]
  - [[#require-lisp][REQUIRE LISP]]
  - [[#eglot-booster][EGLOT BOOSTER]]
- [[#async-savehist-repeat][Async Savehist Repeat]]
- [[#ai][AI]]
- [[#evil-mode][EVIL MODE]]
- [[#eww][EWW]]
- [[#flycheck][FLYCHECK]]
- [[#git][GIT]]
- [[#hungry-delete][HUNGRY-DELETE]]
- [[#keybinding][KEYBINDING]]
- [[#ligature][LIGATURE]]
- [[#search-engine][SEARCH ENGINE]]
  - [[#vertico][VERTICO]]
  - [[#vertico-posframe][VERTICO-POSFRAME]]
  - [[#orderless][ORDERLESS]]
  - [[#consult][CONSULT]]
  - [[#embark][EMBARK]]
  - [[#wgrep][WGREP]]
  - [[#marginalia][MARGINALIA]]
- [[#diminish][DIMINISH]]
- [[#whichkey][WHICHKEY]]
- [[#completion-stuff][COMPLETION STUFF]]
  - [[#company-mode][COMPANY MODE]]
  - [[#corfu][CORFU]]
  - [[#cape][CAPE]]
- [[#org-mode][ORG-MODE]]
- [[#development][DEVELOPMENT]]
  - [[#language][LANGUAGE]]
- [[#popper][POPPER]]
- [[#file-browser][FILE BROWSER]]
  - [[#dired][DIRED]]
  - [[#treemacs][Treemacs]]
  - [[#projectile][PROJECTILE]]
- [[#terminal][TERMINAL]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm toggle]]
  - [[#shell][Shell]]
- [[#snippets][SNIPPETS]]
- [[#rainbow][RAINBOW]]
- [[#sudo-edit][SUDO EDIT]]
- [[#tldr][TlDR]]
- [[#heighlight-todo-list][HEIGHLIGHT TODO LIST]]
- [[#transparency][TRANSPARENCY]]
- [[#ui-stuff][UI STUFF]]
  - [[#icons][ICONS]]
  - [[#theme][THEME]]
  - [[#dashboard][DASHBOARD]]
  - [[#page-break-lines][PAGE BREAK LINES]]
  - [[#fonts][FONTS]]
  - [[#indent][INDENT]]
  - [[#formating][FORMATING]]
  - [[#perspective][PERSPECTIVE]]
- [[#visual-fill-column][Visual Fill Column]]

* VANILA *EMACS* CONFIG
 #+BEGIN_SRC elisp
    (menu-bar-mode -1)
    (tool-bar-mode -1)
    (fringe-mode -1)
    (scroll-bar-mode -1)
    (display-battery-mode t)
    (electric-pair-mode 1) ;; auto paire
    (global-subword-mode 1) ;; global line number
    (global-visual-line-mode t)
    (global-display-line-numbers-mode 1)
    (global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
    (visual-line-mode nil) ;; Kind of like word-wrap

    (setq use-dialog-box nil)
    (setq use-file-dialog nil)
    (setq make-backup-files nil)
    (setq auto-save-default nil)
    (setq locale-coding-system 'utf-8)
    (defalias 'yes-or-no-p 'y-or-n-p)
    ;;; improve scrolling exprience
    (setq scroll-step 1)
    (setq scroll-conservatively 10000)
    (setq auto-window-vscroll nil)

   (global-set-key [escape] 'keyboard-escape-quit)
   (global-set-key (kbd "C-=") 'text-scale-increase)
   (global-set-key (kbd "C--") 'text-scale-decrease)
   (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
   (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
   ;; Faster loading
    (setq gc-cons-threshold (* 384 1024 1024)
       gc-cons-percentage 1.6)
     ;; Do not load outdeted bytecode files;
     (setq load-prefer-newer t)

 ;; Increase for lsp batter performance.
 (setq read-process-output-max (* 3 1024 1024))

 ;; default 800
 (setq max-lisp-eval-depth 10000)

 (setq package-enable-at-startup nil)


  (setq visual-fill-column-width 160
        visual-fill-column-center-text t) ;; ;; Configure fill width
 ;; set custom file for emacs internal variables
 (setq custom-file (concat user-emacs-directory "custom.el")) 
 (load custom-file 'noerror)
#+END_SRC
*** locale
#+begin_src elisp
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+end_src
* PACKAGES MANAGER AND OTHER SCRIPT
** IMPORT LISP DIRECTORY
#+BEGIN_SRC elisp
(defvar scripts-dir (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path scripts-dir)
#+end_src
** REQUIRE LISP
#+begin_src emacs-lisp
(require 'elpaca-setup)
(require 'buffer_move)
(require 'hide-mode-line)
(require 'exec-path-from-shell)
#+END_SRC

** EGLOT BOOSTER
#+begin_src emacs-lisp
(require 'eglot)
(fset #'jsonrpc--log-event #'ignore)
#+end_src

* Async Savehist Repeat
#+begin_src emacs-lisp
;;; Emacs look SIGNIFICANTLY less often which is a good thing.
;;; asynchronous bytecode compilation and various other actions makes
(use-package async
  :ensure t
  :after dired
  :init
  (dired-async-mode 1))

(use-package savehist
  :ensure nil
  :defer 2
  :init
  (savehist-mode t)
  ;; So I can always jump back to wear I left of yesterday
  (add-to-list 'savehist-additional-variables 'global-mark-ring))

(use-package repeat
  :ensure nil
  :defer 10
  :init
  (repeat-mode +1))

#+end_src

* AI
#+begin_src emacs-lisp
(use-package gptel
 :config
 (setq gptel-default-mode 'org-mode)
 (setq gptel-model "gemini-pro"
      gptel-backend (gptel-make-gemini "Gemini"
                    :key "AIzaSyCZ8KNE1MiGPK_av8GC7QSfX0gkFHFaAUk"
                    :stream t))
 ;; Together.ai offers an OpenAI compatible API
 (gptel-make-openai "TogetherAI"         ;Any name you want
  :host "api.together.xyz"
  :key "034dc79db5eb2889e37553de64645e3fb3e7b9261d80e1dcf6c6c5f11acd909c"
  :stream t
  :models '("mistralai/Mixtral-8x7B-Instruct-v0.1"
            "codellama/CodeLlama-13b-Instruct-hf"
            "codellama/CodeLlama-34b-Instruct-hf"))
 (gptel-make-openai "Anyscale" 
   :host "api.endpoints.anyscale.com"
   :key "esecret_5ct3wfyw2njvs7pkrkqh1g2zrx"
   :models '(
            "mistralai/Mixtral-8x7B-Instruct-v0.1")))
(add-hook 'gptel-post-stream-hook 'gptel-auto-scroll)
(add-hook 'gptel-post-response-hook 'gptel-end-of-response)
#+end_src
* EVIL MODE
#+begin_src emacs-lisp
(use-package evil
    :init      ;; tweak evil's configuration before loading it
    (setq evil-want-integration t  ;; This is optional since it's already set to t by default.
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)  ;; Adds vim-like C-r redo functionality
    (evil-mode))
(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer dired))
  (add-to-list 'evil-collection-mode-list 'help) ;; evilify help mode
  (evil-collection-init))
;; Using RETURN to follow links in Org/Evil 
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil))
  ;; Setting RETURN key in org-mode to follow links
(setq org-return-follows-link  t)

(use-package evil-tutor)
;;Mapping "jk" to Escape in Emacs' evil-mode
(use-package evil-escape
  :config
  ;; Set the key sequence you want to use for escaping
  (setq-default evil-escape-key-sequence "jk")
  ;; Adjust the delay if needed
  (setq-default evil-escape-delay 0.2)
  ;; Enable Evil Escape mode globally
  (evil-escape-mode 1))

(use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))
#+end_src
* EWW 
#+begin_src emacs-lisp
(use-package eww
    :ensure nil
    :config
    (setq eww-enable-experimental-features t)
    (setq eww-enable-javascript nil))

    (add-hook 'eww-mode-hook
              (lambda ()
                (visual-fill-column-mode t)
                (display-line-numbers-mode nil)))
#+end_src
* FLYCHECK
#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
#+end_src
* GIT
#+begin_src emacs-lisp
(use-package git-link)
#+end_src
* HUNGRY-DELETE
Hungry Delete is a minor-mode that causes deletion to delete all whitespace in the direction you are deleting. Works exactly like c-hungry-delete-mode, which is where the code was from. This just packages it up to be easier to use in other modes.
#+begin_src emacs-lisp
(use-package hungry-delete
   :ensure t
   :defer t
   :config (global-hungry-delete-mode))
#+end_src
* KEYBINDING
Goto this file -> [[file:./keybinding.el][KEYBINDING]]
key binding with the help *general* package.
#+begin_src emacs-lisp
(load (expand-file-name "keybinding.el" user-emacs-directory))
#+end_src
*** Key-chord
#+begin_src emacs-lisp
;(use-package key-chord
;  :ensure t)
#+end_src
* LIGATURE
#+begin_src emacs-lisp
(use-package ligature
  :ensure t
  :config
  ;; Enable the "www" ligature in every possible major mode
  (ligature-set-ligatures 't '("www"))
  (ligature-set-ligatures '(prog-mode
                           org-mode)
                          '("|||>" "<|||" "<==>" "<!--" "####" "~~>" "***" "||=" "||>"
                                       ":::" "::=" "=:=" "===" "==>" "=!=" "=>>" "=<<" "=/=" "!=="
                                       "!!." ">=>" ">>=" ">>>" ">>-" ">->" "->>" "-->" "---" "-<<"
                                       "<~~" "<~>" "<*>" "<||" "<|>" "<$>" "<==" "<=>" "<=<" "<->"
                                       "<--" "<-<" "<<=" "<<-" "<<<" "<+>" "</>" "###" "#_(" "..<"
                                       "..." "+++" "/==" "///" "_|_" "www" "&&" "^=" "~~" "~@" "~="
                                       "~>" "~-" "**" "*>" "*/" "||" "|}" "|]" "|=" "|>" "|-" "{|"
                                       "[|" "]#" "::" ":=" ":>" ":<" "$>" "==" "=>" "!=" "!!" ">:"
                                       ">=" ">>" ">-" "-~" "-|" "->" "--" "-<" "<~" "<*" "<|" "<:"
                                       "<$" "<=" "<>" "<-" "<<" "<+" "</" "#{" "#[" "#:" "#=" "#!"
                                       "##" "#(" "#?" "#_" "%%" ".=" ".-" ".." ".?" "+>" "++" "?:"
                                       "?=" "?." "??" ";;" "/*" "/=" "/>" "//" "__" "~~" "(*" "*)"
                                       "\\\\" "://"))
  ;; Enable traditional ligature support in eww-mode, if the
  ;; `variable-pitch' face supports it
  (ligature-set-ligatures 'eww-mode '("ff" "fi" "ffi"))
  (global-ligature-mode t))
#+end_src
* SEARCH ENGINE
** VERTICO
The `vertico' package applies a vertical layout to the minibuffer. It also pops up the minibuffer eagerly so we can see the available
options without further interactions.  This package is very fast and "just works", though it also is highly customisable in case we
need to modify its behaviour.
#+begin_src emacs-lisp
(use-package vertico
  :ensure t
  :config
  (setq vertico-cycle t)
  (setq vertico-resize nil)
  (vertico-mode 1))
#+end_src
** VERTICO-POSFRAME
#+begin_src emacs-lisp
(use-package vertico-posframe)
(setq vertico-multiform-commands
      '((consult-line
         posframe
         (vertico-posframe-poshandler . posframe-poshandler-frame-top-center)
         (vertico-posframe-border-width . 15)
         ;; NOTE: This is useful when emacs is used in both in X and
         ;; terminal, for posframe do not work well in terminal, so
         ;; vertico-buffer-mode will be used as fallback at the
         ;; moment.
         (vertico-posframe-fallback-mode . vertico-buffer-mode))
        (t posframe)))
(setq vertico-posframe-parameters '((left-fringe . 5) (right-fringe . 5)))
(setq vertico-posframe-mode 1)
#+end_src
** ORDERLESS
The `orderless' package lets the minibuffer use an out-of-order pattern matching algorithm.  It matches space-separated words or
regular expressions in any order.  In its simplest form, something like "ins pac" matches `package-menu-mark-install' as well as
`package-install'.  This is a powerful tool because we no longer need to remember exactly how something is named.
#+begin_src emacs-lisp
(use-package orderless
  :demand t
  :config
  (setq completion-styles '(orderless flex)
        completion-category-overrides '((eglot (styles . (orderless flex))))))
#+end_src
** CONSULT
The `consult' package provides lots of commands that are enhanced variants of basic, built-in functionality.  One of the headline
features of `consult' is its preview facility, where it shows in another Emacs window the context of what is currently matched in
the minibuffer.  Here I define key bindings for some commands you may find useful.  The mnemonic for their prefix is "alternative
search" (as opposed to the basic C-s or C-r keys).
#+begin_src emacs-lisp
(use-package consult
  :ensure t
  :bind (;; A recursive grep
         ("M-s M-g" . consult-grep)
         ;; Search for files names recursively
         ("M-s M-f" . consult-find)
         ;; Search through the outline (headings) of the file
         ("M-s M-o" . consult-outline)
         ;; Search the current buffer
         ("M-s M-l" . consult-line)
         ;; Switch to another buffer, or bookmarked file, or recently
         ;; opened file.
         ("M-s M-b" . consult-buffer)))
#+end_src
** EMBARK
;; The `embark' package lets you target the thing or context at point ;; and select an action to perform on it.  Use the `embark-act'
;; command while over something to find relevant commands.
#+begin_src emacs-lisp
(use-package embark
  :ensure t
  :bind (("C-." . embark-act)
         :map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export)))
(use-package embark-consult
  :ensure t)
#+end_src
** WGREP
The `wgrep' packages lets us edit the results of a grep search while inside a `grep-mode' buffer.  All we need is to toggle the
editable mode, make the changes, and then type C-c C-c to confirm
or C-c C-k to abort.
#+begin_src emacs-lisp
(use-package wgrep
  :ensure t
  :bind ( :map grep-mode-map
          ("e" . wgrep-change-to-wgrep-mode)
          ("C-x C-q" . wgrep-change-to-wgrep-mode)
          ("C-c C-c" . wgrep-finish-edit)))

;; The built-in `savehist-mode' saves minibuffer histories.  Vertico can then use that information to put recently selected options at the top.
;; Further reading: https://protesilaos.com/emacs/dotemacs#h:25765797-27a5-431e-8aa4-cc890a6a913a
(savehist-mode 1)

;; The built-in `recentf-mode' keeps track of recently visited files.  You can then access those through the `consult-buffer' interface or
;; with `recentf-open'/`recentf-open-files'.
;; I do not use this facility, because the files I care about are either in projects or are bookmarked.
(recentf-mode 1)
#+end_src
** MARGINALIA
#+begin_src emacs-lisp
(use-package marginalia
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'right)
  :init
  (marginalia-mode 1))
#+end_src
* DIMINISH
This package implements hiding or abbreviation of the mode line displays (lighters) of minor-modes.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src
* WHICHKEY
#+begin_src emacs-lisp
(use-package which-key
  :init
    (which-key-mode 1)
  :config
  (setq which-key-side-window-location 'bottom
	  which-key-sort-order #'which-key-key-order-alpha
	  which-key-sort-uppercase-first nil
	  which-key-add-column-padding 1
	  which-key-max-display-columns nil
	  which-key-min-display-lines 6
	  which-key-side-window-slot -10
	  which-key-side-window-max-height 0.25
	  which-key-idle-delay 0.8
	  which-key-max-description-length 25
	  which-key-allow-imprecise-window-fit nil
	  which-key-separator " → " ))
#+end_src
* COMPLETION STUFF
** COMPANY MODE
#+begin_src emacs-lisp
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers nil)
  (company-tooltip-align-annotations 't)
  (global-company-mode nil))

(use-package company-box
  :disabled t
  :after company
  :diminish
  :hook (company-mode . company-box-mode))


#+end_src
** TODO CORFU
Code Completion 
#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    ;; Optional customizations
    :custom
    (corfu-cycle t)                 ; Allows cycling through candidates
    (corfu-auto t)                  ; Enable auto completion
    (corfu-auto-prefix 0)
    (corfu-auto-delay 0.2)
    (corfu-popupinfo-delay '(0.3 . 0.2))
    (corfu-preview-current 'insert) ; insert previewed candidate
    (corfu-preselect 'prompt)
    (corfu-on-exact-match nil)      ; Don't auto expand tempel snippets
    ;; Optionally use TAB for cycling, default is `corfu-complete'.
    :bind (:map corfu-map
		("M-SPC"      . corfu-insert-separator)
		("TAB"        . corfu-next)
		([tab]        . corfu-next)
		("S-TAB"      . corfu-previous)
		([backtab]    . corfu-previous)
		("S-<return>" . corfu-insert)
		("RET"        . corfu-insert))

    :init
    (global-corfu-mode)
    (corfu-history-mode)
    (corfu-popupinfo-mode))

    (setq read-extended-command-predicate #'command-completion-default-include-p)
  (use-package nerd-icons-corfu
    :ensure t
    :config
      (add-to-list '
corfu-margin-formatters #'nerd-icons-corfu-formatter))

  (use-package corfu-terminal
    :ensure t)
#+end_src
** CAPE
Cape has the super power to transform Company backends into Capfs and merge multiple Capfs into a Super-Capf! These transformers allow you to still take advantage of Company backends even if you are not using Company as frontend.
#+begin_src  emacs-lisp
(use-package cape
  :ensure t
  :defer 10
  :bind (("C-c p p" . completion-at-point) ;; capf
         ("C-c p t" . complete-tag)        ;; etags
         ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
         ("C-c p h" . cape-history)
         ("C-c p f" . cape-file)
         ("C-c p k" . cape-keyword)
         ("C-c p s" . cape-elisp-symbol)
         ("C-c p e" . cape-elisp-block)
         ("C-c p a" . cape-abbrev)
         ("C-c p l" . cape-line)
         ("C-c p w" . cape-dict)
         ("C-c p :" . cape-emoji)
         ("C-c p \\" . cape-tex)
         ("C-c p _" . cape-tex)
         ("C-c p ^" . cape-tex)
         ("C-c p &" . cape-sgml)
         ("C-c p r" . cape-rfc1345))
  :init
  ;; Add `completion-at-point-functions', used by `completion-at-point'.
  (defun my/add-shell-completion ()
    (interactive)
    (cl-pushnew #'cape-history completion-at-point-functions)
    (cl-pushnew #'pcomplete-completions-at-point completion-at-point-functions))
  (add-hook 'shell-mode-hook #'my/add-shell-completion nil t)

  :config
    (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block)
    ;;(add-to-list 'completion-at-point-functions #'cape-elisp-symbol)
    ;;(add-to-list 'completion-at-point-functions #'cape-history)
    ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
    ;;(add-to-list 'completion-at-point-functions #'cape-tex)
    ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
    ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
    ;;(add-to-list 'completion-at-point-functions #'cape-abbrev)
    ;;(add-to-list 'completion-at-point-functions #'cape-dict)
    ;;(add-to-list 'completion-at-point-functions #'cape-line)

    ;; Ensure that pcomplete does not write to the buffer
    ;; Silence then pcomplete capf, no errors or messages!
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster)
    (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-silent)
    ;; and behaves as a pure `completion-at-point-function'.
    (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-purify))

#+end_src

* ORG-MODE
Otherwise, org-tempo is broken when you try to <s TAB...
#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda ()
           (setq-local electric-pair-inhibit-predicate
                   `(lambda (c)
                  (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))))
#+end_src
*** BULLETS
#+begin_src emacs-lisp
(use-package org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))) 
(add-hook 'org-mode-hook (lambda () (visual-fill-column-mode t)))
#+end_src
*** CUSTOMS FACE
  #+begin_src emacs-lisp
    (custom-set-faces
     '(org-level-1 ((t (:inherit outline-1 :height 1.3))))
     '(org-level-2 ((t (:inherit outline-2 :height 1.25))))
     '(org-level-3 ((t (:inherit outline-3 :height 1.225))))
     '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
     '(org-level-5 ((t (:inherit outline-5 :height 1.15))))
     '(org-level-6 ((t (:inherit outline-5 :height 1.125))))
     '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
  #+end_src
*** ORG-JUARNAL
#+begin_export emacs-lisp
(use-package org-journal
  :ensure t
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq
      org-journal-dir "~/.notes/org/journal"
      org-journal-date-prefix "#+TITLE: "
      org-journal-time-format "%I:%M %p "
      org-journal-time-prefix "* "
      org-journal-date-format "%A, %d/%m/%Y"
      org-journal-file-format "%d-%m-%Y.org"))
    #+end_export
*** ORG-ROAM
#+begin_src emacs-lisp
(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory (file-truename "~/.notes/org"))
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ("C-c n j" . org-roam-dailies-capture-today)) ;; Dailies
  :config
  ;; If you're using a vertical completion framework, you might want a more informative completion interface
  (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (require 'org-roam-protocol))
#+end_src

*** ORG-ROAM-UI
#+begin_src emacs-lisp
(use-package websocket
    :after org-roam)
(use-package org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src

*** Org-modern
#+begin_src emacs-lisp
(use-package org-modern
  :ensure t
  :config
  ;;(with-eval-after-load 'org (global-org-modern-mode))
  )
#+end_src
*** SNIPPET
#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src
*** TOC
#+begin_src emacs-lisp

(setq user-full-name "Azizul Islam"
      user-mail-address "azizul7m@gmail.com")

(use-package toc-org
    :commands toc-org-enable
    :init
    (add-hook 'org-mode-hook 'toc-org-enable))
  #+end_src
***  Pandoc
#+begin_src emacs-lisp
(use-package org-pandoc-import
  :ensure (:host github
             :repo "tecosaur/org-pandoc-import"
             :files ("*.el" "filters" "preprocessors")))
#+end_src
***  Pandoc export
#+begin_src emacs-lisp
(use-package ox-pandoc
  :ensure (:host github
             :repo "kawabata/ox-pandoc"
             :files ("*.el" "filters" "preprocessors"))
  :config
    ;; special settings for beamer-pdf and latex-pdf exporters
    (setq org-pandoc-options-for-beamer-pdf '((pdf-engine . "pdfroff")))
    (setq org-pandoc-options-for-latex-pdf '((pdf-engine . "pdflatex")))
    ;; special extensions for markdown_github output
    (setq org-pandoc-format-extensions '(markdown_github+pipe_tables+raw_html))
  )
#+end_src
* DEVELOPMENT
** LANGUAGE

*** Rust
#+begin_src emacs-lisp
(use-package rustic
  :ensure t
  :init
  (setq rustic-lsp-client 'eglot))

(use-package cargo-mode
  :hook
  (rustic-mode . cargo-minor-mode)
  :config
  (setq compilation-scroll-output t))
#+end_src
*** Nix
#+begin_src emacs-lisp
(use-package nix-mode
  :mode
  ("\\.nix\\'"))
#+end_src
*** 
*** TODO Typescript
DEADLINE: <2024-03-20 বুধ>
fix corfu completion
#+begin_src emacs-lisp
(use-package web-mode
  :ensure t
  :defer t
  :config
  (setq web-mode-markup-indent-offset 2
        web-mode-css-indent-offset 2
        web-mode-code-indent-offset 2
        web-mode-style-padding 2
        web-mode-script-padding 2
        web-mode-enable-auto-closing t
        web-mode-enable-auto-opening t
        web-mode-enable-auto-pairing t
        web-mode-enable-auto-indentation t)
  (add-hook 'web-mode-hook 'emmet-mode)
  :mode
  (("\\.html\\'" . web-mode)
   ("\\.php\\'" . web-mode)
   ("\\.ejs\\'" . web-mode)
   ("\\.tsx\\'" . web-mode)))


(use-package tide
  :ensure t
  :defer t
  :hook ((typescript-mode . setup-tide-mode)
         (before-save . tide-format-before-save)))

(defun setup-tide-mode ()
  "Set up Tide mode."
  (interactive)
  (tide-setup)
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eldoc-mode +1)
  (tide-hl-identifier-mode +1)
  (corfu-mode -1)
  (company-mode +1))

(defun my-web-mode-hook ()
  "Hook for web-mode."
  (when (and (string-equal "tsx" (file-name-extension buffer-file-name))
             (locate-dominating-file default-directory "tsconfig.json"))
    (setup-tide-mode)))

(add-hook 'web-mode-hook 'my-web-mode-hook)


(use-package typescript-mode
  :ensure t
  :hook (typescript-mode-hook )
  :mode
  (("\\.ts\\'" . typescript-mode)))
(defun typescript-mode-setup()
  (flycheck-mode +1)
  (setq flycheck-check-syntax-automatically '(save mode-enabled))
  (eglot-ensure))

(add-hook 'typescript-mode-hook 'evil-collection-typescript-mode-setup)
;; Enable ESLint or TSLint for linting
;; Ensure you have ESLint or TSLint installed globally or locally in your project
;; You can choose either ESLint or TSLint by commenting/uncommenting the relevant lines below

;; For ESLint
;; (add-hook 'typescript-mode-hook 'eglint-initialize)
;; (add-hook 'web-mode-hook 'eglint-initialize)

;; For TSLint
;;(add-hook 'typescript-mode-hook 'eglot-tslint)
;(add-hook 'web-mode-hook 'eglot-tslint)

(use-package json-mode)


(use-package emmet-mode
  :ensure t)

#+end_src

***** Treesit 
#+begin_src emacs-lisp
(require 'treesit)

(setq treesit-language-source-alist
      '((bash . ("git@github.com:tree-sitter/tree-sitter-bash.git"))
        (c . ("git@github.com:tree-sitter/tree-sitter-c.git"))
        (cpp . ("git@github.com:tree-sitter/tree-sitter-cpp.git"))
        (css . ("git@github.com:tree-sitter/tree-sitter-css.git"))
        (elixir . ("git@github.com:elixir-lang/tree-sitter-elixir.git"))
        (heex . ("git@github.com:phoenixframework/tree-sitter-heex.git"))
        (go . ("git@github.com:tree-sitter/tree-sitter-go.git"))
        (html . ("git@github.com:tree-sitter/tree-sitter-htm.git"))
        (javascript . ("git@github.com:tree-sitter/tree-sitter-javascript.git"))
        (json . ("git@github.com:tree-sitter/tree-sitter-json.git"))
        (lua . ("git@github.com:Azganoth/tree-sitter-lua.git"))
        (make . ("git@github.com:alemuller/tree-sitter-make.git"))
        (ocaml . ("git@github.com:tree-sitter/tree-sitter-ocaml.git" "ocaml/src" "ocaml"))
        (python . ("git@github.com:tree-sitter/tree-sitter-python.git"))
        (php . ("git@github.com:tree-sitter/tree-sitter-php.git"))
        (typescript . ("git@github.com:tree-sitter/tree-sitter-typescript.git" "typescript/src" "typescript" "tsx/src"))
        (ruby . ("git@github.com:tree-sitter/tree-sitter-ruby.git"))
        (rust . ("git@github.com:tree-sitter/tree-sitter-rust.git"))
        (sql . ("git@github.com:m-novikov/tree-sitter-sql.git"))
        (toml . ("git@github.com:tree-sitter/tree-sitter-toml.git"))
        (zig . ("git@github.com:GrayJack/tree-sitter-zig.git"))))
(require 'ansi-color)

(defun colorize-compilation-buffer ()
  (ansi-color-apply-on-region compilation-filter-start (point-max)))

(add-hook 'compilation-filter-hook 'colorize-compilation-buffer)
#+end_src
***  DevOop
#+begin_src emacs-lisp
(use-package terraform-mode)
(use-package dockerfile-mode)

(add-to-list 'auto-mode-alist '("\\.tf\\'" . terraform-mode))
(add-to-list 'auto-mode-alist '("\\Dockerfile" . dockerfile-mode))
#+end_src
*** Direnv
#+begin_src emacs-lisp
(use-package envrc)
#+end_src
* POPPER
#+begin_src emacs-lisp
(use-package popper
  :ensure t ; or :straight t
  :bind (("C-`"   . popper-toggle)
         ("M-`"   . popper-cycle)
         ("C-M-`" . popper-toggle-type)
         ("M-q"     . popper-kill-latest-popup))
  :init
  (setq popper-reference-buffers
        '("\\*Messages\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
            "*Flymake diagnostics.*"
            "\\*eldoc\\*"
            "\\*compilation\\*"
            "\\*rustic-"
            "^*tex"
            "\\*Ement Notifications\\*"
            "Output\\*$"
            "\\*Async Shell Command\\*"
            "\\*Dtache Shell Command\\*"
            "\\*mu4e-update\\*"
            "\\*GDB.*out\\*"
            "\\*vterm\\*"
          help-mode
          compilation-mode))
  (popper-mode +1)
  (popper-echo-mode +1))                ; For echo area hints
#+end_src
* FILE BROWSER
** DIRED
#+begin_src emacs-lisp
(use-package dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("jepg" . "sxiv")
                                ("png" . "sxiv")
                                ("pdf" . "sioyek")
                                ("mkv" . "vlc")
                                ("mp4" . "vlc"))))
(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src
** Treemacs
#+begin_src emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  :config
  (progn
    (setq
         treemacs-width 35
         treemacs-recenter-after-project-jump 'always)
    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode 'always)
    (treemacs-hide-gitignored-files-mode nil))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t d"   . treemacs-select-directory)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))


(use-package treemacs-projectile
  :after (treemacs projectile)
  :ensure t)

(use-package treemacs-icons-dired
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)

(use-package treemacs-persp ;;treemacs-perspective if you use perspective.el vs. persp-mode
  :after (treemacs persp-mode) ;;or perspective vs. persp-mode
  :ensure t
  :config (treemacs-set-scope-type 'Perspectives))
#+end_src
** PROJECTILE
#+begin_src emacs-lisp
(use-package projectile
   :ensure t
   :defer t
   :init
   (projectile-mode 1))
#+end_src
* TERMINAL
** Vterm
#+begin_src emacs-lisp
(use-package vterm
:config
(setq shell-file-name "/bin/sh"
      vterm-max-scrollback 5000))
#+end_src
** Vterm toggle
#+begin_src emacs-lisp

(use-package vterm-toggle
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  ;; Modeline customization for vterm buffers
  (defun my-vterm-cleanup-ui ()
    (setq mode-line-format nil)
    (setq mode-line-format-in-non-selected-windows nil))

  (add-hook 'vterm-mode-hook #'my-vterm-cleanup-ui)
  (add-hook 'vterm-mode-hook (lambda () (display-line-numbers-mode 0)))
  
   (add-to-list 'display-buffer-alist
                '((lambda (buffer-or-name _)
                      (let ((buffer (get-buffer buffer-or-name)))
                        (with-current-buffer buffer
                          (or (equal major-mode 'vterm-mode)
                              (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                   (display-buffer-reuse-window display-buffer-at-bottom)
                   (reusable-frames . visible)
                   (window-height . 0.3)))
  )
#+end_src
** Shell
*** 
#+begin_src emacs-lisp
(add-to-list 'exec-path "~/.npm_global/bin")
#+end_src
*** Eshell 
#+begin_src emacs-lisp
  (use-package eshell-syntax-highlighting
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))
(setq eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src
* SNIPPETS
#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :bind ("M-+" . yas-insert-snippet)
  :config
  (setopt yas-snippet-dirs (append yas-snippet-dirs
                                   '("~/.notes/org/snippets")))
  (yas-global-mode +1)
  (add-to-list 'hippie-expand-try-functions-list #'yas-hippie-try-expand))

(use-package yasnippet-snippets
  :ensure t :after yasnippet)
(use-package yasnippet-capf
  :ensure t
  :after yasnippet
  :hook ((prog-mode . yas-setup-capf)
         (text-mode . yas-setup-capf)
         (lsp-mode  . yas-setup-capf)
         (sly-mode  . yas-setup-capf))
  :bind (("C-c y" . yasnippet-capf)
         ("M-+"   . yas-insert-snippet))
  :config
  (defun yas-setup-capf ()
    (setq-local completion-at-point-functions
                (cons 'yasnippet-capf
                      completion-at-point-functions)))
  (push 'yasnippet-capf completion-at-point-functions))
#+end_src
* RAINBOW
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src
* SUDO EDIT
#+begin_src emacs-lisp
(use-package sudo-edit)
#+end_src
* TlDR
#+begin_src emacs-lisp
(use-package tldr)
#+end_src
* HEIGHLIGHT TODO LIST
#+begin_src emacs-lisp
(use-package hl-todo
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))
#+end_src
* TRANSPARENCY
With Emacs version 29, true transparency has been added.  I have turned transparency off by setting the alpha to ‘100’.  If you want some slight transparency, try setting alpha to ‘90’.  Of course, if you set alpha to ‘0’, the background of Emacs would completely transparent.
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha-background . 90)) ; For all new frames henceforth
#+end_src
* UI STUFF
** ICONS
#+begin_src emacs-lisp
(use-package all-the-icons
  :ensure t
  :if (display-graphic-p)
  :config
  (setq inhibit-compacting-font-caches t))

(use-package all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))

(use-package all-the-icons-ibuffer
  :ensure t
  :hook (ibuffer-mode . all-the-icons-ibuffer-mode))

(use-package all-the-icons-completion
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))

#+end_src
** THEME
#+BEGIN_SRC elisp


(use-package spaceway-theme
  :ensure nil
  :load-path "lisp/spaceway/"
  :config
  ;;(load-theme 'spaceway t)
  (setenv "SCHEME" "dark"))

 (use-package doom-themes
 :ensure t
 :config
 (setq doom-themes-enable-bold nil  
         doom-themes-enable-italic t) ; if nil, italics is universally disabled
 (setq doom-themes-treemacs-theme "doom-colors")
 (doom-themes-treemacs-config)
 (load-theme 'doom-one t)
 )




(use-package doom-modeline
  :ensure t
  :config
    (setq doom-modeline-height 17)
    (setq  doom-modeline-hud t)
    (setq doom-modeline-icon t)
    (setq doom-modeline-lsp-icon t)
    (setq doom-modeline-height 1)
    (set-face-attribute 'mode-line nil :height 100)
    (set-face-attribute 'mode-line-inactive nil :height 100)
   :init (doom-modeline-mode 1))




#+END_SRC
** DASHBOARD
#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.face")  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-vertically-center-content t)
  (setq dashboard-display-icons-p t)     ; display icons on both GUI and terminal
  (setq dashboard-icon-type 'nerd-icons)  ; use `all-the-icons' package

  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  :config
  ;;(add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  ;;(add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (add-hook 'dashboard-mode-hook #'hide-mode-line-mode)
  (dashboard-setup-startup-hook))
#+end_src
** PAGE BREAK LINES
#+begin_src emacs-lisp
(use-package page-break-lines
  :ensure t
  :init
  (global-page-break-lines-mode)
)
#+end_src
** FONTS
#+begin_src emacs-lisp
(set-face-attribute 'default nil
    :font "Iosevka"
    :height 105
    :weight 'medium)
#+end_src
** INDENT 
#+begin_src emacs-lisp
(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 2)
(eval-after-load 'org-indent '(diminish 'org-indent-mode))
(add-hook 'org-mode-hook 'org-indent-mode)
(setq org-edit-src-content-indentation 0)
(use-package highlight-indent-guides
  :ensure t
  :defer t
  :hook (prog-mode . highlight-indent-guides-mode)
  :config
  (setq highlight-indent-guides-method 'character)
  (setq highlight-indent-guides-character ?\|)
  (setq highlight-indent-guides-responsive 'top))
#+end_src
** FORMATING
#+begin_src emacs-lisp
(use-package format-all
	 :ensure t)
#+end_src
** PERSPECTIVE
#+begin_src emacs-lisp
(use-package perspective
  :custom
  ;; NOTE! I have also set 'SCP =' to open the perspective menu.
  ;; I'm only setting the additional binding because setting it
  ;; helps suppress an annoying warning message.
  (persp-mode-prefix-key (kbd "C-c M-p"))
  :init 
  (persp-mode)
  :config
  ;; Sets a file to write to when we save states
  (setq persp-state-default-file "~/.config/emacs/sessions"))
;; This will group buffers by persp-name in ibuffer.
(add-hook 'ibuffer-hook
          (lambda ()
            (persp-ibuffer-set-filter-groups)
            (unless (eq ibuffer-sorting-mode 'alphabetic)
              (ibuffer-do-sort-by-alphabetic))))
;; Automatically save perspective states to file when Emacs exits.
(add-hook 'kill-emacs-hook #'persp-state-save)
#+end_src
* Visual Fill Column
#+begin_src emacs-lisp
(use-package visual-fill-column
  :ensure t
  :config
  (setq-default visual-fill-column-center-text t))

#+end_src
