#+STARTUP: unfold
#+title: Emacs Config
#+author: Azizul Islam
#+email: azizul7m@gmail.com
#+OPTIONS: toc:2
* TABLE OF CONTENT                                                     :toc:
- [[#vanila-emacs-config][VANILA *EMACS* CONFIG]]
- [[#packages-manager-and-other-script][PACKAGES MANAGER AND OTHER SCRIPT]]
  - [[#import-lisp-directory][IMPORT LISP DIRECTORY]]
  - [[#require-lisp][REQUIRE LISP]]
- [[#async-savehist-repeat][ASYNC SAVEHIST REPEAT]]
- [[#ai][AI]]
  - [[#gptel][Gptel]]
  - [[#gptel-quick][gptel-quick]]
- [[#completion-stuff][COMPLETION STUFF]]
  - [[#company-mode][COMPANY MODE]]
  - [[#corfu][CORFU]]
  - [[#cape][CAPE]]
  - [[#eldoc][Eldoc]]
  - [[#consult][CONSULT]]
- [[#development][DEVELOPMENT]]
  - [[#codespaces][CODESPACES]]
  - [[#direnv][DIRENV]]
  - [[#eglot][EGLOT]]
  - [[#lsp][LSP]]
  - [[#language][LANGUAGE]]
  - [[#tree-sitter][TREE-SITTER]]
  - [[#ts-fold][TS-FOLD]]
  - [[#debug][Debug]]
- [[#emacs-application-framework][EMACS APPLICATION FRAMEWORK]]
- [[#evil-mode][EVIL MODE]]
- [[#eww][EWW]]
- [[#env][ENV]]
- [[#flycheck][FLYCHECK]]
- [[#git][GIT]]
- [[#hungry-delete][HUNGRY-DELETE]]
- [[#irc][IRC]]
- [[#keybinding][KEYBINDING]]
- [[#ligature][LIGATURE]]
- [[#search-engine][SEARCH ENGINE]]
  - [[#vertico][VERTICO]]
  - [[#vertico-posframe][VERTICO-POSFRAME]]
  - [[#orderless][ORDERLESS]]
  - [[#consult-1][CONSULT]]
  - [[#embark][EMBARK]]
  - [[#wgrep][WGREP]]
  - [[#marginalia][MARGINALIA]]
- [[#diminish][DIMINISH]]
- [[#whichkey][WHICHKEY]]
- [[#org-mode][ORG-MODE]]
  - [[#markdown-mode][Markdown mode]]
  - [[#enote][Enote]]
- [[#popper][POPPER]]
- [[#file-browser][FILE BROWSER]]
  - [[#dired][DIRED]]
  - [[#projectile][PROJECTILE]]
  - [[#treemacs][TREEMACS]]
- [[#terminal][TERMINAL]]
  - [[#vterm][VTERM]]
  - [[#vterm-toggle][VTERM TOGGLE]]
- [[#remote][REMOTE]]
- [[#snippets][SNIPPETS]]
- [[#rainbow][RAINBOW]]
  - [[#rainbow-1][RAINBOW]]
  - [[#selected-window][selected-window]]
- [[#sudo-edit][SUDO EDIT]]
- [[#tldr][TlDR]]
- [[#heighlight-todo-list][HEIGHLIGHT TODO LIST]]
- [[#transparency][TRANSPARENCY]]
- [[#ui-stuff][UI STUFF]]
  - [[#posframe][POSFRAME]]
  - [[#icons][ICONS]]
  - [[#theme][THEME]]
  - [[#dashboard][DASHBOARD]]
  - [[#page-break-lines][PAGE BREAK LINES]]
  - [[#fonts][FONTS]]
  - [[#indent][INDENT]]
  - [[#pluntuml][PluntUML]]
  - [[#indent-guides][INDENT-GUIDES]]
  - [[#formating][FORMATING]]
  - [[#perspective][PERSPECTIVE]]
- [[#visual-stuff][VISUAL STUFF]]
- [[#vm][VM]]

* VANILA *EMACS* CONFIG
 #+BEGIN_SRC elisp
      (menu-bar-mode -1)
      (tool-bar-mode -1)
      (fringe-mode -1)

      (scroll-bar-mode -1)
      (save-place-mode 1)


      (display-battery-mode t)
      (electric-pair-mode 1) ;; auto paire
      (global-subword-mode 1) ;; global line number
      (global-display-line-numbers-mode 1)
      (global-auto-revert-mode t)  ;; Automatically show changes if the file has changed
      (blink-cursor-mode -1)
      (global-hl-line-mode 1)

      (setq-default truncate-lines t)

      (setq scroll-margin 8)
      (setq use-dialog-box nil)
      (setq use-file-dialog nil)
      (setq make-backup-files nil)
      (setq auto-save-default nil)
      (setq locale-coding-system 'utf-8)
      (defalias 'yes-or-no-p 'y-or-n-p)
      ;;; improve scrolling exprience
      (setq scroll-step 1)
      (setq scroll-conservatively 10000)
      (setq auto-window-vscroll nil)

     (global-set-key [escape] 'keyboard-escape-quit)
     (global-set-key (kbd "C-=") 'text-scale-increase)
     (global-set-key (kbd "C--") 'text-scale-decrease)
     (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
     (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
     (global-set-key (kbd "M-j") 'consult-buffer)

     ;; Faster loading
      (setq gc-cons-threshold (* 384 1024 1024)
         gc-cons-percentage 1.6)
       ;; Do not load outdeted bytecode files;
       (setq load-prefer-newer t)

   ;; Increase for lsp batter performance.
   (setq read-process-output-max (* 3 1024 1024))

   ;; default 800
   (setq max-lisp-eval-depth 10000)

   (setq package-enable-at-startup nil)


    (setq visual-fill-column-width 160
          visual-fill-column-center-text t) ;; ;; Configure fill width
   ;; set custom file for emacs internal variables
   (setq custom-file (concat user-emacs-directory "custom.el"))
   (load custom-file 'noerror)
#+END_SRC
*** locale
#+begin_src elisp
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+end_src
* PACKAGES MANAGER AND OTHER SCRIPT
** IMPORT LISP DIRECTORY
#+BEGIN_SRC elisp
(defvar scripts-dir (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path scripts-dir)
#+end_src
** REQUIRE LISP
#+begin_src emacs-lisp
;;(require 'elpaca-setup)
(require 'straight)
(require 'buffer_move)
(require 'hide-mode-line)
#+END_SRC

* ASYNC SAVEHIST REPEAT
#+begin_src emacs-lisp
;;; Emacs look SIGNIFICANTLY less often which is a good thing.
;;; asynchronous bytecode compilation and various other actions makes
(use-package async
  :straight t
  :after dired
  :init
  (dired-async-mode 1))

(use-package savehist
  :straight nil
  :defer 2
  :init
  (savehist-mode t)
  ;; So I can always jump back to wear I left of yesterday
  (add-to-list 'savehist-additional-variables 'global-mark-ring))

(use-package repeat
  :straight nil
  :defer 10
  :init
  (repeat-mode +1))

#+end_src

* AI
** Gptel
#+begin_src emacs-lisp
(use-package gptel
:straight t
 :config
 ;;(setq gptel-default-mode 'org-mode)
 (gptel-make-gemini "Gemini" :key "AIzaSyCZ8KNE1MiGPK_av8GC7QSfX0gkFHFaAUk" :stream t)
 ;; Together.ai offers an OpenAI compatible API
(setq gptel-model   "mistralai/Mixtral-8x7B-Instruct-v0.1"
 gptel-backend
 (gptel-make-openai "TogetherAI"
   :host "api.together.xyz"
   :key "034dc79db5eb2889e37553de64645e3fb3e7b9261d80e1dcf6c6c5f11acd909c"
   :stream t
   :models '(;; has many more, check together.ai
             "mistralai/Mixtral-8x7B-Instruct-v0.1"
             "codellama/CodeLlama-13b-Instruct-hf"
             "codellama/CodeLlama-34b-Instruct-hf")))

 (gptel-make-openai "Anyscale"
   :host "api.endpoints.anyscale.com"
   :key "esecret_5ct3wfyw2njvs7pkrkqh1g2zrx"
   :models '(
            "mistralai/Mixtral-8x7B-Instruct-v0.1")))

(global-set-key (kbd "C-c <return>") 'gptel-send)
(add-hook 'gptel-post-stream-hook 'gptel-auto-scroll)
(add-hook 'gptel-post-response-functions 'gptel-end-of-response)
#+end_src
** gptel-quick
#+begin_src emacs-lisp
#+end_src
* COMPLETION STUFF
** COMPANY MODE
#+begin_src emacs-lisp
(use-package company
  :defer 2
  :diminish
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers nil)
  (company-tooltip-align-annotations 't))

(use-package company-box
  :disabled t
  :after company
  :diminish
  :hook (company-mode . company-box-mode))

(setq company-global-modes nil)

#+end_src
** TODO CORFU
Code Completion
#+begin_src emacs-lisp
(use-package corfu
  :straight t
  :custom
  (corfu-cycle t)                 ; Allows cycling through candidates
  (corfu-auto t)                  ; Enable auto completion
  (corfu-auto-prefix 0)
  (corfu-auto-delay 0.2)
  (corfu-popupinfo-delay '(0.2 . 0.1))
  (corfu-preview-current 'insert) ; Insert previewed candidate
  (corfu-preselect 'prompt)
  (corfu-quit-no-match 'separator)
  (corfu-on-exact-match nil)
  :bind (:map corfu-map
         ("TAB" . corfu-next)
         ([tab] . corfu-next)
         ("S-TAB" . corfu-previous)
         ([backtab] . corfu-previous)
         ("RET" . corfu-insert))
  :init
  (corfu-history-mode)
  (corfu-popupinfo-mode)
  (global-corfu-mode))

(setq read-extended-command-predicate #'command-completion-default-include-p)

(use-package nerd-icons-corfu
  :straight t
  :config
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

(use-package corfu-terminal
  :straight t)
#+end_src
** CAPE
Cape has the super power to transform Company backends into Capfs and merge multiple Capfs into a Super-Capf! These transformers allow you to still take advantage of Company backends even if you are not using Company as frontend.
#+begin_src  emacs-lisp
(use-package cape
  :straight t
  :bind (("C-c p p" . completion-at-point) ;; capf
         ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
         ("C-c p f" . cape-file)
         ("C-c p k" . cape-keyword)
         ("C-c p s" . cape-elisp-symbol))
  :init
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-keyword)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block))

#+end_src
** Eldoc
#+begin_src emacs-lisp
(use-package eldoc-box
  :config
  (setq eldoc-box-max-pixel-height 450
        eldoc-box-max-pixel-width 600
        eldoc-box-show-help-tooltip t
        eldoc-box-tooltip-delay 500))
#+end_src
** CONSULT
#+begin_src emacs-lisp

#+end_src
* DEVELOPMENT
** CODESPACES
This package provides support for connecting to GitHub Codespaces in Emacs via TRAMP.
#+begin_src emacs-lisp
(use-package codespaces
  :straight t
  :config (codespaces-setup))
(setq tramp-ssh-controlmaster-options "")
(setq vc-handled-backends '(Git))
;;(add-to-list 'tramp-remote-path 'tramp-own-remote-path)
#+end_src
** DIRENV
#+begin_src emacs-lisp
 (use-package direnv
  :config
  (direnv-mode))

(use-package dotenv-mode);
(add-to-list 'auto-mode-alist '("\\.env\\..*\\'" . dotenv-mode)) ;;
#+end_src
** EGLOT
#+begin_src emacs-lisp
(use-package eglot
  :hook ((rust-mode nix-mode) . eglot-ensure)
  :bind (:map eglot-mode-map
              ("C-c C-a" . eglot-code-actions)
              ("C-c C-r" . eglot-rename)
              ("C-c C-d" . eglot-menu))
  :config
  (add-to-list 'eglot-server-programs
               '((tsx-ts-mode typescript-ts-mode javascript-mode) . ("typescript-language-server" "--stdio")))
  (add-to-list 'eglot-server-programs
               '((css-mode scss-mode html-mode) . ("tailwindcss-language-server" "--stdio")))
  (add-to-list 'eglot-server-programs
               '((rust-mode rustic-mode) . ("~/.cargo/bin/rust-analyzer" :initializationOptions
                                            (:procMacro (:enable t)
                                                         :cargo (:buildScripts (:enable t)
                                                                                :features "all"))))))


(fset #'jsonrpc--log-event #'ignore)
(setq eglot-server-json-parser #'json-parse-string-no-itaewc)
#+end_src

** LSP
#+begin_src emacs-lisp
#+end_src
** LANGUAGE
*** DevOop
#+begin_src emacs-lisp
(use-package terraform-mode)
(use-package dockerfile-mode)
(use-package docker-compose-mode)

(add-to-list 'auto-mode-alist '("\\.tf\\'" . terraform-mode))
(add-to-list 'auto-mode-alist '("\\Dockerfile" . dockerfile-mode))
(add-to-list 'auto-mode-alist '("\\docker-compose.yml" . docker-compose-mode))
#+end_src
*** JS/TS
#+begin_src emacs-lisp
(use-package typescript-ts-mode
  :straight t
  :mode ("\\.ts\\'" . 'typescript-ts-mode)
  :hook (typescript-mode . 'eglot-ensure)
  :config
  (setq typescript-indent-level 2
	typescript-lsp-extra-server-flags "--log-level=verbose"))
  (add-hook 'tsx-ts-mode-hook #'eglot-ensure)
#+end_src
*** Deno
#+begin_src emacs-lisp
;; (use-package deno-ts-mode
;;   :straight t
;;   :mode (("\\.ts\\'" . 'deno-ts-mode)
;;          ("\\tsx\\'" . 'deno-tsx-mode)))

#+end_src
*** Nix
#+begin_src emacs-lisp
(use-package nix-mode
 :mode ("\\.nix\\'")
 :hook (nix-mode . 'eglot-ensure)
 :straight t)
#+end_src
*** Rust
#+begin_src emacs-lisp
(use-package rustic
  :straight t
  :init
  (setq rustic-lsp-server-extra-args "--debug")
  (setq rustic-format-on-save nil)
  (setq rustic-lsp-client 'eglot))


(use-package cargo-mode
  :hook
  (rustic-mode . cargo-minor-mode)
  :config
  (setq compilation-scroll-output t))
#+end_src

#+begin_src emacs-lisp
;; (with-eval-after-load "lsp-rust"
;;  (lsp-register-client
;;   (make-lsp-client
;;    :new-connection (lsp-stdio-connection
;;                     (lambda ()
;;                       `(,(or (executable-find
;;                               (cl-first lsp-rust-analyzer-server-command))
;;                              (lsp-package-path 'rust-analyzer)
;;                              "rust-analyzer")
;;                         ,@(cl-rest lsp-rust-analyzer-server-args))))
;;    :remote? t
;;    :major-modes '(rust-mode rustic-mode)
;;    :initialization-options 'lsp-rust-analyzer--make-init-options
;;    :notification-handlers (ht<-alist lsp-rust-notification-handlers)
;;    :action-handlers (ht ("rust-analyzer.runSingle" #'lsp-rust--analyzer-run-single))
;;    :library-folders-fn (lambda (_workspace) lsp-rust-library-directories)
;;    :after-open-fn (lambda ()
;;                     (when lsp-rust-analyzer-server-display-inlay-hints
;;                       (lsp-rust-analyzer-inlay-hints-mode)))
;;    :ignore-messages nil
;;    :server-id 'rust-analyzer-remote)))
#+end_src
*** Solidity
#+begin_src emacs-lisp
;; Set up the Solidity mode and related packages
(use-package solidity-mode
  :straight t
  :mode ("\\.sol\\'" . solidity-mode))
#+end_src
*** Tailwindcss
#+begin_src emacs-lisp :tangle yes
#+end_src

#+end_src
*** Web Mode
#+begin_src emacs-lisp
(use-package web-mode
  :straight t
  :hook format-all-mode
  :defer t
  :config
  (setq web-mode-markup-indent-offset 2
        web-mode-css-indent-offset 2
        web-mode-code-indent-offset 2
        web-mode-style-padding 2
        web-mode-script-padding 2
        web-mode-enable-auto-closing t
        web-mode-enable-auto-opening t
        web-mode-enable-auto-pairing t
        web-mode-enable-auto-indentation t)
  (add-hook 'web-mode-hook 'emmet-mode)
  :mode
  (("\\.html\\'" . web-mode)
   ("\\.php\\'" . web-mode)
   ("\\.ejs\\'" . web-mode)))

(use-package json-mode
  :mode
  (("\\.json\\'" . json-mode)))

(use-package emmet-mode
  :straight t)
#+end_src
** TREE-SITTER
#+begin_src emacs-lisp
(use-package treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  :config
  (setq treesit-auto-langs '(javascript typescript tsx css html rustic))
  (treesit-auto-add-to-auto-mode-alist '(javascript typescript tsx css html rustic))
  (global-treesit-auto-mode))


#+end_src
** TS-FOLD
#+begin_src emacs-lisp
(use-package ts-fold
  :straight (ts-fold :type git :host github :repo "emacs-tree-sitter/ts-fold"))
#+end_src
** Debug
#+begin_src emacs-lisp
#+end_src
* EMACS APPLICATION FRAMEWORK
#+begin_src emacs-lisp
;; (use-package eaf
;;   :straight (eaf :type git :host github :repo "manateelazycat/emacs-application-framework" :file ("*"))
;;   :init
;;   (use-package epc :defer t :ensure t)
;;   (use-package ctable :defer t :ensure t)
;;   (use-package deferred :defer t :ensure t)
;;   (use-package s :defer t :ensure t))

#+end_src
* EVIL MODE
#+begin_src emacs-lisp
(use-package evil
  :straight t
    :init      ;; tweak evil's configuration before loading it
    (setq evil-want-integration t  ;; This is optional since it's already set to t by default.
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)  ;; Adds vim-like C-r redo functionality
    (evil-mode))
(use-package evil-collection
  :config
  (setq evil-collection-mode-list '(calendar dashboard dired ediff info magit ibuffer dired elpaca))
  (add-to-list 'evil-collection-mode-list 'help) ;; evilify help mode
  (evil-collection-init))
;; Using RETURN to follow links in Org/Evil
;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
(with-eval-after-load 'evil-maps
  (define-key evil-motion-state-map (kbd "SPC") nil)
  (define-key evil-motion-state-map (kbd "K") nil)
  (define-key evil-motion-state-map (kbd "RET") nil)
  (define-key evil-motion-state-map (kbd "TAB") nil)
  (define-key evil-normal-state-map (kbd "C-.") 'embark-act)
  (define-key evil-visual-state-map (kbd "C-.") 'embark-act))
  ;; Setting RETURN key in org-mode to follow links
(setq org-return-follows-link  t)

;;Mapping "jk" to Escape in Emacs' evil-mode
(use-package evil-escape
  :config
  ;; Set the key sequence you want to use for escaping
  (setq-default evil-escape-key-sequence "jk")
  ;; Adjust the delay if needed
  (setq-default evil-escape-delay 0.2)
  ;; Enable Evil Escape mode globally
  (evil-escape-mode 1))

(use-package evil-surround
  :straight t
  :config
  (global-evil-surround-mode 1))
#+end_src
* EWW
#+begin_src emacs-lisp
(use-package eww
    :straight t
    :config
    (setq eww-enable-experimental-features t)
    (setq eww-enable-javascript t))

    (add-hook 'eww-mode-hook
              (lambda ()
                (visual-fill-column-mode t)
                (display-line-numbers-mode nil)))
#+end_src
* ENV
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns x))
  :straight t
  :config
  (exec-path-from-shell-initialize))
#+end_src
* FLYCHECK
#+begin_src emacs-lisp
(use-package flycheck
  :bind (:map flycheck-mode-map
              ("M-n" . flycheck-previous-error)
              ("M-p" . flycheck-next-error))
  :custom (flycheck-display-errors-delay .2)
  :init (global-flycheck-mode))
#+end_src
* GIT
#+begin_src emacs-lisp
(use-package git-link
  :straight t)

(use-package magit)
(use-package git-gutter 
    :straight t
    :config
    (setq git-gutter:window-width 1)
    :init
    (global-git-gutter-mode))

  (use-package git-timemachine)

#+end_src
* HUNGRY-DELETE
Hungry Delete is a minor-mode that causes deletion to delete all whitespace in the direction you are deleting. Works exactly like c-hungry-delete-mode, which is where the code was from. This just packages it up to be easier to use in other modes.
#+begin_src emacs-lisp
(use-package hungry-delete
   :straight t
   :defer t
   :config (global-hungry-delete-mode))
#+end_src
* IRC
#+begin_src emacs-lisp
(setq erc-autojoin-mode t
   erc-server "irc.libera.chat"
   erc-autojoin-channels-alist '(("irc.libera.chat" "#systemcrafters" "#emacs" "##rust"))
   erc-nick "Azizul7m"
   erc-user-full-name "Azizul Islam"  ; And this!
   erc-track-shorten-start 8
   erc-interpret-mirc-color t
   erc-query-display 'buffer
   erc-kill-buffer-on-part t
   ;; messages
   erc-hide-list '("JOIN" "PART" "QUIT")
   ;; tracking -----------------------------------------------------------
   erc-track-exclude-types '("JOIN" "NICK" "PART" "QUIT" "MODE"
                             "324" "329" "332" "333" "353" "477")
   erc-auto-query 'bury)
;;(erc-spelling-mode 1)
#+end_src
* KEYBINDING
Goto this file -> [[file:./keybinding.el][KEYBINDING]]
key binding with the help *general* package.
#+begin_src emacs-lisp
(load (expand-file-name "keybinding.el" user-emacs-directory))
#+end_src
* LIGATURE
#+begin_src emacs-lisp
(use-package ligature
  :straight t
  :config
  (ligature-set-ligatures 't '("www"))
  (global-ligature-mode t))

;; (use-package fira-code-mode
;;   :straight t
;;   :custom (fira-code-mode-disabled-ligatures '("x" "=>"))  ; ligatures you don't want
;;   :hook prog-mode)
#+end_src
* SEARCH ENGINE
** VERTICO
The `vertico' package applies a vertical layout to the minibuffer. It also pops up the minibuffer eagerly so we can see the available
options without further interactions.  This package is very fast and "just works", though it also is highly customisable in case we
need to modify its behaviour.
#+begin_src emacs-lisp
(use-package vertico
  :straight t
  :config
  (setq vertico-cycle t)
  (setq vertico-resize nil)
  (vertico-mode 1))
#+end_src
** VERTICO-POSFRAME
#+begin_src emacs-lisp
(use-package vertico-posframe)
(setq vertico-multiform-commands
      '((consult-line
         posframe
         (vertico-posframe-poshandler . posframe-poshandler-frame-top-center)
         (vertico-posframe-border-width . 15)
         (vertico-posframe-width . 850)
         (vertico-posframe-height . 600)
         (vertico-posframe-fallback-mode . vertico-buffer-mode))
        (t posframe)))
(setq vertico-posframe-parameters '((left-fringe . 5) (right-fringe . 5)))
(setq vertico-posframe-mode 1)
#+end_src
** ORDERLESS
The `orderless' package lets the minibuffer use an out-of-order pattern matching algorithm.  It matches space-separated words or
regular expressions in any order.  In its simplest form, something like "ins pac" matches `package-menu-mark-install' as well as
`package-install'.  This is a powerful tool because we no longer need to remember exactly how something is named.
#+begin_src emacs-lisp
(use-package orderless
  :demand t
  :config
  (setq completion-styles '(orderless flex)
        completion-category-overrides '((eglot (styles . (orderless flex))))))
#+end_src
** CONSULT
The `consult' package provides lots of commands that are enhanced variants of basic, built-in functionality.  One of the headline
features of `consult' is its preview facility, where it shows in another Emacs window the context of what is currently matched in
the minibuffer.  Here I define key bindings for some commands you may find useful.  The mnemonic for their prefix is "alternative
search" (as opposed to the basic C-s or C-r keys).
#+begin_src emacs-lisp
(use-package consult
  :straight t
  :bind (;; A recursive grep
         ("M-s M-g" . consult-grep)
         ;; Search for files names recursively
         ("M-s M-f" . consult-find)
         ;; Search through the outline (headings) of the file
         ("M-s M-o" . consult-outline)
         ;; Search the current buffer
         ("M-s M-l" . consult-line)
         ;; Switch to another buffer, or bookmarked file, or recently
         ;; opened file.
         ("M-s M-b" . consult-buffer)))
#+end_src
** EMBARK
;; The `embark' package lets you target the thing or context at point ;; and select an action to perform on it.  Use the `embark-act'
;; command while over something to find relevant commands.
#+begin_src emacs-lisp
(use-package embark
  :straight t
  :bind (("C-." . embark-act)
         :map minibuffer-local-map
         ("C-c C-c" . embark-collect)
         ("C-c C-e" . embark-export)))
(use-package embark-consult
  :straight t)
#+end_src
** WGREP
The `wgrep' packages lets us edit the results of a grep search while inside a `grep-mode' buffer.  All we need is to toggle the
editable mode, make the changes, and then type C-c C-c to confirm
or C-c C-k to abort.
#+begin_src emacs-lisp
(use-package wgrep
  :straight t
  :bind ( :map grep-mode-map
          ("e" . wgrep-change-to-wgrep-mode)
          ("C-x C-q" . wgrep-change-to-wgrep-mode)
          ("C-c C-c" . wgrep-finish-edit)))
(savehist-mode 1)
(recentf-mode 1)
#+end_src
** MARGINALIA
#+begin_src emacs-lisp
(use-package marginalia
  :custom
  (marginalia-max-relative-age 0)
  (marginalia-align 'right)
  :init
  (marginalia-mode 1))
#+end_src
* DIMINISH
This package implements hiding or abbreviation of the mode line displays (lighters) of minor-modes.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src
* WHICHKEY
#+begin_src emacs-lisp
(use-package which-key
:straight t
  :init
    (which-key-mode 1)
  :config
  (setq which-key-side-window-location 'bottom
	  which-key-sort-order #'which-key-key-order-alpha
	  which-key-sort-uppercase-first nil
	  which-key-add-column-padding 1
	  which-key-max-display-columns nil
	  which-key-min-display-lines 4
	  which-key-side-window-slot -10
	  which-key-side-window-max-height 0.25
	  which-key-idle-delay 0.5
	  which-key-max-description-length 25
	  which-key-allow-imprecise-window-fit nil
	  which-key-separator " → " ))
#+end_src
* ORG-MODE
Otherwise, org-tempo is broken when you try to <s TAB...
#+begin_src emacs-lisp
(straight-use-package 'org)
 ;; Hook to customize electric pair behavior in org-mode
(add-hook 'org-mode-hook
          (lambda ()
            (setq visual-fill-column-mode t
                  line-number-mode -1)))
            
#+end_src

*** BULLETS
#+begin_src emacs-lisp
(use-package org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))

#+end_src
*** CUSTOMS FACE
  #+begin_src emacs-lisp
    (custom-set-faces
     '(org-level-1 ((t (:inherit outline-1 :height 1.3))))
     '(org-level-2 ((t (:inherit outline-2 :height 1.25))))
     '(org-level-3 ((t (:inherit outline-3 :height 1.225))))
     '(org-level-4 ((t (:inherit outline-4 :height 1.2))))
     '(org-level-5 ((t (:inherit outline-5 :height 1.15))))
     '(org-level-6 ((t (:inherit outline-5 :height 1.125))))
     '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))
  #+end_src
*** ORG-JUARNAL
#+begin_export emacs-lisp
(use-package org-journal
  :straight t
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq
      org-journal-dir "~/.notes/org/journal"
      org-journal-date-prefix "#+TITLE: "
      org-journal-time-format "%I:%M %p "
      org-journal-time-prefix "* "
      org-journal-date-format "%A, %d/%m/%Y"
      org-journal-file-format "%d-%m-%Y.org"))
    #+end_export
*** Org-Note
#+begin_src emacs-lisp
(use-package orgnote
  :general (:states '(normal visual)
                    :config
                    (setq orgnote-enable-roam-sync-p t)
                    :keymaps 'org-mode-map
                    "SPC np" 'orgnote-publish-file))
#+end_src
*** ORG-ROAM
#+begin_src emacs-lisp
(use-package org-roam
  :straight t
  :init
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory (file-truename "~/.notes/org"))
  (org-roam-completion-everywhere t)
  :bind (("C-c n l" . org-roam-buffer-toggle)
         ("C-c n f" . org-roam-node-find)
         ("C-c n g" . org-roam-graph)
         ("C-c n i" . org-roam-node-insert)
         ("C-c n c" . org-roam-capture)
         ("C-c n j" . org-roam-dailies-capture-today)) ;; Dailies
  :config
  ;; If you're using a vertical completion framework, you might want a more informative completion interface
  (setq org-roam-node-display-template (concat "${title:*} " (propertize "${tags:10}" 'face 'org-tag)))
  (org-roam-db-autosync-mode)
  ;; If using org-roam-protocol
  (org-roam-setup))
#+end_src
*** ORG-ROAM-UI
#+begin_src emacs-lisp
(use-package websocket
    :after org-roam)
(use-package org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+end_src

*** Org-modern
#+begin_src emacs-lisp
(use-package org-modern
  :straight t
  :config
  (with-eval-after-load 'org (global-org-modern-mode)))
#+end_src

*** Org Notion
#+begin_src emacs-lisp
(use-package org-present
  :straight t)
#+end_src
*** SNIPPET
#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src
*** TOC
#+begin_src emacs-lisp
(setq user-full-name "Azizul Islam"
      user-mail-address "azizul7m@gmail.com")

(use-package toc-org
    :commands toc-org-enable
    :init
    (add-hook 'org-mode-hook 'toc-org-enable))
  #+end_src
*** Pandoc
#+begin_src emacs-lisp
(use-package org-pandoc-import
  :straight (:host github
             :repo "tecosaur/org-pandoc-import"
             :files ("*.el" "filters" "preprocessors")))
#+end_src
*** Pandoc export
#+begin_src emacs-lisp
(use-package ox-pandoc
  :straight (:host github
             :repo "kawabata/ox-pandoc"
             :files ("*.el" "filters" "preprocessors"))
  :config
    ;; special settings for beamer-pdf and latex-pdf exporters
    (setq org-pandoc-options-for-beamer-pdf '((pdf-engine . "pdfroff")))
    (setq org-pandoc-options-for-latex-pdf '((pdf-engine . "pdflatex")))
    ;; special extensions for markdown_github output
    (setq org-pandoc-format-extensions '(markdown_github+pipe_tables+raw_html))
  )
#+end_src
** Markdown mode
#+begin_src elisp
(use-package markdown-mode
  :straight t
  :config
  (setq markdown-fontify-code-blocks-natively t))
#+end_src
** Enote
#+begin_src emacs-lisp
(require 'enote)
(global-set-key (kbd "C-c n e c") 'create-enote-frame)
(global-set-key (kbd "C-c n e d") 'enote--delete-note)
(global-set-key (kbd "C-c n e s") 'enote--save-buffer-to-file)
(global-set-key (kbd "C-c n e m") 'enote--make-frame)
#+end_src
* POPPER
#+begin_src emacs-lisp
(use-package popper
  :straight t ; or :straight t
  :bind (("C-`"   . popper-toggle)
         ("M-`"   . popper-cycle)
         ("C-M-`" . popper-toggle-type)
         ("M-q"     . popper-kill-latest-popup))
  :init
  (setq popper-reference-buffers
        '("\\*Messages\\*"
          "Output\\*$"
          "\\*Async Shell Command\\*"
            "*Flymake diagnostics.*"
            "\\*eldoc\\*"
            "\\*compilation\\*"
            "\\*rustic-"
            "^*tex"
            "\\*Ement Notifications\\*"
            "Output\\*$"
            "\\*Async Shell Command\\*"
            "\\*Dtache Shell Command\\*"
            "\\*mu4e-update\\*"
            "\\*GDB.*out\\*"
            "\\*vterm\\*"
          help-mode
          compilation-mode))
  (popper-mode +1)
  (popper-echo-mode +1))                ; For echo area hints
#+end_src
* FILE BROWSER
** DIRED
#+begin_src emacs-lisp
(use-package dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("jepg" . "sxiv")
                                ("png" . "sxiv")
                                ("pdf" . "sioyek")
                                ("mkv" . "vlc")
                                ("mp4" . "vlc"))))
(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
#+end_src

** PROJECTILE
#+begin_src emacs-lisp
(use-package projectile
   :straight t
   :defer t
   :config
         (setq projectile-enable-caching t
               projectile-file-exists-remote-cache-expire nil)
   :init
   (projectile-mode 1))
#+end_src
** TREEMACS
#+begin_src emacs-lisp
(defun my/treemacs-setup ()
  "Customize settings for treemacs buffer."
  (display-line-numbers-mode -1))

(use-package treemacs
  :straight t
  :defer t
  :config
  (progn
    (setq
     treemacs-width 35
     treemacs-recenter-after-project-jump 'always)
    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode 'always)
    (treemacs-hide-gitignored-files-mode nil)
    )

  :bind
  (:map global-map
        ("<space>"    . treemacs) ; Leader key binding
        ("M-0"        . treemacs-select-window)
        ("C-x t 1"    . treemacs-delete-other-windows)
        ("C-x t t"    . treemacs)
        ("C-x t d"    . treemacs-select-directory)
        ("C-x t B"    . treemacs-bookmark)
        ("C-x t C-t"  . treemacs-find-file)
        ("C-x t M-t"  . treemacs-find-tag))
  :hook
  (treemacs-mode . my/treemacs-setup))

  (with-eval-after-load 'treemacs
    (define-key treemacs-mode-map (kbd "w") nil)
    (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action))

(use-package treemacs-all-the-icons
  :after (treemacs all-the-icons)
  :config
  (treemacs-load-theme "all-the-icons"))

(use-package treemacs-evil)

(use-package treemacs-projectile
  :after (treemacs projectile)
  :straight t
  :config
  (setq treemacs-header-function #'treemacs-projectile-create-header))

(defun my/treemacs-projectile-toggle ()
  "Open Treemacs and add the current Projectile project."
  (interactive)
  (treemacs)
  (treemacs-add-and-display-current-project))

(add-hook 'projectile-after-switch-project-hook #'my/treemacs-projectile-toggle)


(use-package treemacs-icons-dired
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :straight t)

(use-package treemacs-persp
  :after (treemacs persp-mode)
  :straight t
  :config (treemacs-set-scope-type 'Perspectives))

#+end_src
* TERMINAL
** VTERM
#+begin_src emacs-lisp
(use-package vterm
:config
(setq shell-file-name "/bin/sh"
      vterm-max-scrollback 5000))
#+end_src
** VTERM TOGGLE
#+begin_src emacs-lisp

(use-package vterm-toggle
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
  ;; Modeline customization for vterm buffers
  (defun my-vterm-cleanup-ui ()
    (setq mode-line-format nil)
    (setq mode-line-format-in-non-selected-windows nil))

  (add-hook 'vterm-mode-hook #'my-vterm-cleanup-ui)
  (add-hook 'vterm-mode-hook (lambda () (display-line-numbers-mode 0)))

   (add-to-list 'display-buffer-alist
                '((lambda (buffer-or-name _)
                      (let ((buffer (get-buffer buffer-or-name)))
                        (with-current-buffer buffer
                          (or (equal major-mode 'vterm-mode)
                              (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                   (display-buffer-reuse-window display-buffer-at-bottom)
                   (reusable-frames . visible)
                   (window-height . 0.3)))
  )
#+end_src
* REMOTE
#+begin_src emacs-lisp
(setq tramp-default-method "ssh")
  (setq tramp-default-remote-shell "/bin/bash")
#+end_src
* SNIPPETS
#+begin_src emacs-lisp
(use-package yasnippet
  :straight t
  :bind ("M-+" . yas-insert-snippet)
  :config
  (setopt yas-snippet-dirs (append yas-snippet-dirs
                                   '("~/.notes/org/snippets")))
  (yas-global-mode +1)
  (add-to-list 'hippie-expand-try-functions-list #'yas-hippie-try-expand))

(use-package yasnippet-snippets
  :straight t :after yasnippet)
(use-package yasnippet-capf
  :straight t
  :after yasnippet
  :hook ((prog-mode . yas-setup-capf)
         (text-mode . yas-setup-capf)
         (sly-mode  . yas-setup-capf))
  :bind (("C-c y" . yasnippet-capf)
         ("M-+"   . yas-insert-snippet))
  :config
  (defun yas-setup-capf ()
    (setq-local completion-at-point-functions
                (cons 'yasnippet-capf
                      completion-at-point-functions)))
  (push 'yasnippet-capf completion-at-point-functions))
#+end_src
* RAINBOW
** RAINBOW
#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :config
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src
** selected-window
#+begin_src emacs-lisp
#+end_src
* SUDO EDIT
#+begin_src emacs-lisp
(use-package sudo-edit)
#+end_src
* TlDR
#+begin_src emacs-lisp
(use-package tldr)
#+end_src
* HEIGHLIGHT TODO LIST
#+begin_src emacs-lisp
(use-package hl-todo
  :straight t
  :hook ((org-mode . hl-todo-mode)
         (prog-mode . hl-todo-mode))
  :config
  (setq hl-todo-highlight-punctuation ":"
        hl-todo-keyword-faces
        `(("TODO"       warning bold)
          ("FIXME"      error bold)
          ("HACK"       font-lock-constant-face bold)
          ("REVIEW"     font-lock-keyword-face bold)
          ("NOTE"       success bold)
          ("DEPRECATED" font-lock-doc-face bold))))
#+end_src
* TRANSPARENCY
With Emacs version 29, true transparency has been added.  I have turned transparency off by setting the alpha to ‘100’.  If you want some slight transparency, try setting alpha to ‘90’.  Of course, if you set alpha to ‘0’, the background of Emacs would completely transparent.
#+begin_src emacs-lisp
(set-frame-parameter nil 'alpha-background 80) ; For current frame
(add-to-list 'default-frame-alist '(alpha-background . 80)) ; For all new frames henceforth
#+end_src
* UI STUFF
** POSFRAME
#+begin_src emacs-lisp
(use-package posframe
  :straight t
  :after dashboard)
#+end_src
** ICONS
#+begin_src emacs-lisp
(use-package all-the-icons
  :straight t
  :config
  (setq inhibit-compacting-font-caches t))

(use-package all-the-icons-dired
  :hook (dired-mode . (lambda () (all-the-icons-dired-mode t))))

(use-package all-the-icons-ibuffer
  :straight t
  :hook (ibuffer-mode . all-the-icons-ibuffer-mode))

(use-package all-the-icons-completion
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))

#+end_src
** THEME
#+BEGIN_SRC elisp
  (use-package timu-spacegrey-theme
  :straight t
  :config
  ;;(load-theme 'timu-spacegrey t)
  (setenv "SCHEME" "dark"))

   (use-package doom-themes
   :straight t
   :config
   (setq doom-themes-enable-bold nil
	   doom-themes-enable-italic t) ; if nil, italics is universally disabled
   (setq doom-themes-treemacs-theme "doom-colors")
   (doom-themes-treemacs-config)
   (load-theme 'doom-one t)
   )

  (use-package doom-modeline
    :straight t
    :config
      (setq doom-modeline-height 17)
      (setq  doom-modeline-hud t)
      (setq doom-modeline-icon t)
      (setq doom-modeline-lsp-icon t)
      (setq doom-modeline-height 1)
      (set-face-attribute 'mode-line nil :height 100)
      (set-face-attribute 'mode-line-inactive nil :height 100)
     :init
     (doom-modeline-mode 1))

#+END_SRC
** DASHBOARD
#+begin_src emacs-lisp
(use-package dashboard
  :straight t
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "~/.face")  ;; use custom image as banner
  (setq dashboard-center-content t) ;; set to 't' for centered content
  (setq dashboard-vertically-center-content t)
  (setq dashboard-display-icons-p t)     ; display icons on both GUI and terminal
  (setq dashboard-icon-type 'nerd-icons)  ; use `all-the-icons' package
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  :config
  ;;(add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  ;;(add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (add-hook 'dashboard-mode-hook #'hide-mode-line-mode)
  (dashboard-setup-startup-hook))
#+end_src
** PAGE BREAK LINES
#+begin_src emacs-lisp
(use-package page-break-lines
  :straight t
  :init
  (global-page-break-lines-mode)
)
#+end_src
** FONTS
#+begin_src emacs-lisp
(set-face-attribute 'default nil
    :font "Iosevka"
    :height 102
    :weight 'regular)

#+end_src
** INDENT
#+begin_src emacs-lisp
(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 2)
(eval-after-load 'org-indent '(diminish 'org-indent-mode))
(add-hook 'org-mode-hook 'org-indent-mode)
(setq org-edit-src-content-indentation 0)
#+end_src

** PluntUML
#+begin_src emacs-lisp
(use-package uniline
  :defer t
  :bind ("C-<insert>"     . uniline-mode)
  :bind ("C-<insertchar>" . uniline-mode)
  :config
  (setq line-spacing nil))
#+end_src
** INDENT-GUIDES
#+begin_src emacs-lisp
(use-package indent-bars
  :straight (indent-bars :type git :host github :repo "jdtsmith/indent-bars")
  :hook (prog-mode . indent-bars-mode)
  :config
  (setq indent-bars-prefer-character "|"))
  (setopt indent-bars-ts-color '(inherit unspecified :blend 0.15))
#+end_src
** FORMATING
#+begin_src emacs-lisp
(use-package apheleia
  :straight t
  :config
  (setq apheleia-global-mode 1)
  (setq apheleia-remote-algorithm 'remote)
  (apheleia-global-mode +1))
#+end_src

*** Combobulate
#+begin_src emacs-lisp
  (use-package combobulate
    :straight t
    :custom
    ;; You can customize Combobulate's key prefix here.
    ;; Note that you may have to restart Emacs for this to take effect!
    (combobulate-key-prefix "C-c o")
    :hook
    ((python-ts-mode . combobulate-mode)
     (js-ts-mode . combobulate-mode)
     (go-mode . go-ts-mode)
     (html-ts-mode . combobulate-mode)
     (css-ts-mode . combobulate-mode)
     (yaml-ts-mode . combobulate-mode)
     (typescript-ts-mode . combobulate-mode)
     (json-ts-mode . combobulate-mode)
     (tsx-ts-mode . combobulate-mode))
    ;; Amend this to the directory where you keep Combobulate's source
    :load-path ("~/Repository/combobulate"))
#+end_src
** PERSPECTIVE
#+begin_src emacs-lisp
(use-package perspective
   :straight t
  :custom
  ;; NOTE! I have also set 'SCP =' to open the perspective menu.
  ;; I'm only setting the additional binding because setting it
  ;; helps suppress an annoying warning message.
  (persp-mode-prefix-key (kbd "C-c M-p"))
  :init
  (persp-mode)
  :config
  ;; Sets a file to write to when we save states
  (setq persp-state-default-file "~/.config/emacs/sessions"))
;; This will group buffers by persp-name in ibuffer.
(add-hook 'ibuffer-hook
          (lambda ()
            (persp-ibuffer-set-filter-groups)
            (unless (eq ibuffer-sorting-mode 'alphabetic)
              (ibuffer-do-sort-by-alphabetic))))
;; Automatically save perspective states to file when Emacs exits.
(add-hook 'kill-emacs-hook #'persp-state-save)
#+end_src
* VISUAL STUFF
#+begin_src emacs-lisp
(use-package visual-fill-column
  :straight t
  :config
  (setq-default visual-fill-column-center-text t))


(use-package writeroom-mode
  :straight t)

#+end_src

* VM
#+begin_src emacs-lisp
(use-package vagrant
  :straight t)
(setq tramp-remote-tramp-use-rsync t)
#+end_src
