# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cb01f8d3-03b5-43c5-94d9-4c78a884a95e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/13D1-AC42";
      fsType = "vfat";
    };

  swapDevices =
    [ 
    	{ device = "/dev/disk/by-uuid/d4a67c7f-4e69-4e2f-9fa5-8eab15933f78"; }
    ];

#HDD
  fileSystems."/home" = {
    device = "/dev/disk/by-label/home";
    fsType = "ext4";
  };

  fileSystems."/home/anower/Soft" = {
    device = "/dev/disk/by-label/Soft_Tuto";
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };
  
  fileSystems."/home/anower/Projects" = {
    device = "/dev/disk/by-label/Projects";
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };


  fileSystems."/home/anower/Entertainment" = {
    device = "/dev/disk/by-label/Entertainment"; 
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };



  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
