# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/014f383c-fe15-4691-baae-00bd422c2265";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/C7C6-0BAA";
      fsType = "vfat";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/c558883f-5108-455c-87d6-59b9286301a2"; } ];


#HDD
  fileSystems."/home/anower/Soft" = {
    device = "/dev/disk/by-label/Soft_Tuto"; # Replace "sdX" with the name of your NTFS-formatted disk
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };


  fileSystems."/home/anower/Projects" = {
    device = "/dev/disk/by-label/Projects"; # Replace "sdX" with the name of your NTFS-formatted disk
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };


  fileSystems."/home/anower/Entertainment" = {
    device = "/dev/disk/by-label/Entertainment"; # Replace "sdX" with the name of your NTFS-formatted disk
    fsType = "ntfs-3g";
    options = [ "defaults" "uid=1000,gid=1000" ];
  };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable= true;
}
