#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Sweet-Dark'
ICONS='Tela circle manjaro dark'
FONT='Ubuntu 10'
# CURSOR='simp1e'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
  ${SCHEMA} gtk-theme "$THEME"
  ${SCHEMA} icon-theme "$ICONS"
  # ${SCHEMA} cursor-theme "$CURSOR"
  ${SCHEMA} font-name "$FONT"
}

apply_themes
