image {
    monitor =
    path = ~/.wallpapers/ocen-wave.png
    size = 150 # lesser side if not 1:1 ratio
    rounding = -1 # negative values mean circle
    border_size = 4
    border_color = rgb(221, 221, 221)

    position = 0, 200
    halign = center
    valign = center
}